In [ ]:
#1.Write a Pandas program to create a dataframe from a dictionary and display it.
#Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

#Expected Output:
#    X   Y   Z
#0  78  84  86
#1  85  94  97
#2  96  89  96
#3  80  83  72
#4  86  86  83

In [ ]:
 import pandas as pd

df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
df

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [ ]:
'''2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
....
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0
'''

"2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\n....\ni         2      Kevin      no    8.0\nj         1      Jonas     yes   19.0\n"

In [ ]:
import numpy as np

df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}, index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [ ]:
"""3. Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
  Summary of the basic information about this DataFrame and its data:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
....
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None"""

"3. Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\n  Summary of the basic information about this DataFrame and its data:\n<class 'pandas.core.frame.DataFrame'>\nIndex: 10 entries, a to j\nData columns (total 4 columns):\n....\ndtypes: float64(1), int64(1), object(2)\nmemory usage: 400.0+ bytes\nNone"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

In [ ]:
df.describe()

           score   attempts
count   8.000000  10.000000
mean   13.562500   1.900000
std     4.693746   0.875595
min     8.000000   1.000000
25%     9.000000   1.000000
50%    13.500000   2.000000
75%    17.125000   2.750000
max    20.000000   3.000000

In [ ]:
df.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [ ]:
df.tail()

      name  score  attempts qualify
f  Michael   20.0         3     yes
g  Matthew   14.5         1     yes
h    Laura    NaN         1      no
i    Kevin    8.0         2      no
j    Jonas   19.0         1     yes

In [ ]:
"""4. Write a Pandas program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
First three rows of the data frame:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5"""

"4. Write a Pandas program to get the first 3 rows of a given DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nFirst three rows of the data frame:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\nc         2  Katherine     yes   16.5"

In [ ]:
df.iloc[:3]

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

In [ ]:
"""5. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
...
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0"""

"5. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nSelect specific columns:\n        name  score\na  Anastasia   12.5\nb       Dima    9.0\nc  Katherine   16.5\n...\nh      Laura    NaN\ni      Kevin    8.0\nj      Jonas   19.0"

In [ ]:
df.iloc[:, :2]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

In [ ]:
"""6. Write a Pandas program to select the specified columns and rows from a given data frame.
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],


'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes"""

"6. Write a Pandas program to select the specified columns and rows from a given data frame.\nSample Python dictionary data and list labels:\nSelect 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n\n\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nSelect specific columns and rows:\n   score qualify\nb    9.0      no\nd    NaN      no\nf   20.0     yes\ng   14.5     yes"

In [ ]:
df.iloc[[1, 3, 5, 6], [1, 3]]

   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

In [ ]:
"""7. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes"""

"7. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nNumber of attempts in the examination is greater than 2:\n      name  score  attempts qualify\nb     Dima    9.0         3      no\nd    James    NaN         3      no\nf  Michael   20.0         3     yes"

In [ ]:
df[(df['attempts']>2) & (df['qualify'] == "no")]

    name  score  attempts qualify
b   Dima    9.0         3      no
d  James    NaN         3      no

In [ ]:
"""8. Write a Pandas program to count the number of rows and columns of a DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Number of Rows: 10
Number of Columns: 4"""

"8. Write a Pandas program to count the number of rows and columns of a DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nNumber of Rows: 10\nNumber of Columns: 4"

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Tenderfoot Fitness 2023 XLSX version for python.xlsx")
df

,Tenderfoot fitness,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,19,Unnamed: 6,RESTART,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,ATTEMPT 3,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Date,Push-ups,Situps,Stretches,Run,NOTES,NaN,Date,Push-ups,Situps,Stretches,Run,NOTES,NaN,Date,Push-ups,Situps,Stretches,Run,NOTES
1,2023-08-20 00:00:00,25,25,14.75,6.5,Sunday,NaN,1930-10-20 00:00:00,19,23,14.75,NaN,NaN,NaN,2023-12-07 00:00:00,22,25,NaN,7,NaN
2,2023-08-21 00:00:00,44,23,14.75,NaN,NaN,NaN,1930-10-21 00:00:00,20,24,14.75,NaN,NaN,NaN,2023-12-08 00:00:00,22,27,14.25,NaN,NaN
3,2023-08-22 00:00:00,35,26,15,NaN,NaN,NaN,1930-10-22 00:00:00,19,22,14.5,NaN,NaN,NaN,2023-12-09 00:00:00,21,28,14.5,NaN,NaN
4,2023-08-23 00:00:00,37,27,14.75,NaN,NaN,NaN,1930-10-23 00:00:00,20,24,14.75,NaN,NaN,NaN,2023-12-10 00:00:00,22,27,14,NaN,NaN
5,2023-08-24 00:00:00,33,26,14.75,6.5,NaN,NaN,1930-10-24 00:00:00,22,26,14.5,NaN,NaN,NaN,2023-12-11 00:00:00,22,26,14.25,NaN,NaN
6,2023-08-25 00:00:00,35,27,15,NaN,NaN,NaN,1930-10-25 00:00:00,21,25,14.5,NaN,NaN,NaN,2023-12-12 00:00:00,23,29,14.25,NaN,NaN
7,2023-08-26 00:00:00,34,27,15,NaN,NaN,NaN,1930-10-26 00:00:00,19,24,14.75,NaN,NaN,NaN,2023-12-13 00:00:00,23,28,14.25,NaN,NaN
8,2023-08-27 00:00:00,33,26,15,NaN,NaN,NaN,1930-10-27 00:00:00,24,26,14.75,NaN,NaN,NaN,2023-12-14 00:00:00,24,30,14.5,7,NaN
9,2023-08-28 00:00:00,34,25,15,NaN,NaN,NaN,1930-10-28 00:00:00,21,25,15,NaN,NaN,NaN,2023-12-15 00:00:00,22,29,14.25,NaN,NaN
10,2023-08-29 00:00:00,35,26,15.25,NaN,NaN,NaN,1930-10-29 00:00:00,22,26,14.75,NaN,NaN,NaN,2023-12-16 00:00:00,23,28,14,NaN,NaN
11,2023-08-30 00:00:00,37,24,15,NaN,NaN,NaN,1930-10-30 00:00:00,23,27,15,NaN,NaN,NaN,2023-12-17 00:00:00,24,29,14.25,NaN,NaN
12,2023-08-31 00:00:00,36,26,15.25,7,NaN,NaN,1930-10-31 00:00:00,22,25,15,NaN,NaN,NaN,2023-12-18 00:00:00,25,28,14.5,NaN,NaN
13,2023-09-01 00:00:00,34,28,15,NaN,NaN,NaN,1930-11-01 00:00:00,21,26,15,NaN,NaN,NaN,2023-12-19 00:00:00,24,29,14.25,NaN,NaN
14,2023-09-02 00:00:00,36,26,15.25,NaN,NaN,NaN,1930-11-02 00:00:00,22,25,14.75,NaN,NaN,NaN,2023-12-20 00:00:00,25,29,14,NaN,NaN
15,2023-09-03 00:00:00,15,24,15,NaN,"FROM NOW ON, REAL PUSH UPS",NaN,1930-11-03 00:00:00,23,27,14.5,NaN,NaN,NaN,2023-12-21 00:00:00,24,28,13.75,No scout meeting (ran 2 miles at school),NaN
16,2023-09-04 00:00:00,16,25,15,NaN,NaN,NaN,1930-11-04 00:00:00,20,27,15,NaN,NaN,NaN,2023-12-22 00:00:00,25,29,14,NaN,NaN
17,2023-09-05 00:00:00,16,26,15,NaN,NaN,NaN,1930-11-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-23 00:00:00,26,28,14,NaN,NaN
18,2023-09-06 00:00:00,17,25,15.25,NaN,NaN,NaN,1930-11-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-24 00:00:00,24,29,14.25,NaN,NaN
19,2023-09-07 00:00:00,17,26,15.25,7,NaN,NaN,1930-11-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-25 00:00:00,25,28,13.75,NaN,NaN
20,2023-09-08 00:00:00,18,27,15,NaN,NaN,NaN,1930-11-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-26 00:00:00,25,30,14,NaN,NaN
21,2023-09-09 00:00:00,20,25,15.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-27 00:00:00,24,30,14.25,NaN,NaN
22,2023-09-10 00:00:00,20,26,15.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-28 00:00:00,25,31,14,Didn't attend troop mtg. Ran 1.5 miles at school,NaN
23,2023-09-11 00:00:00,18,27,15.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-29 00:00:00,25,29,14.5,NaN,NaN
24,2023-09-12 00:00:00,19,24,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-30 00:00:00,24,28,14.25,NaN,NaN
25,2023-09-13 00:00:00,19,27,15.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-31 00:00:00,24,29,14,NaN,NaN
26,2023-09-14 00:00:00,20,25,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01 00:00:00,25,28,14.5,NaN,NaN
27,2023-09-15 00:00:00,20,26,15.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-02 00:00:00,24,29,14.25,NaN,NaN
28,2023-09-16 00:00:00,20,25,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-03 00:00:00,26,30,14.5,NaN,NaN
29,2023-09-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-04 00:00:00,24,29,14,7,NaN
30,2023-09-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-05 00:00:00,25,31,14.25,NaN,NaN
31,2023-09-19 00:00:00,NaN,NaN,NaN,NaN,Tuesday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2023-09-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2023-09-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2023-09-22 00:00:00,NaN,NaN,NaN,NaN,LAST DAY (Scout Meeting),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
"""8. Write a Pandas program to count the number of rows and columns of a DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Number of Rows: 10
Number of Columns: 4"""

"8. Write a Pandas program to count the number of rows and columns of a DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nNumber of Rows: 10\nNumber of Columns: 4"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

print("Number of Rows: ", len(df.axes[0]))
print("Number of Columns: ", len(df.axes[1]))

Number of Rows:  10
Number of Columns:  4

In [ ]:
"""9. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN"""

"9. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nRows where score is missing:\n   attempts   name qualify  score\nd         3  James      no    NaN\nh         1  Laura      no    NaN"

In [ ]:
df[df['score'].isnull()]

    name  score  attempts qualify
3  James    NaN         3      no
7  Laura    NaN         1      no

In [ ]:
"""10. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Rows where score between 15 and 20 (inclusive):
   attempts       name qualify  score
c         2  Katherine     yes   16.5
f         3    Michael     yes   20.0
j         1      Jonas     yes   19.0"""

"10. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nRows where score between 15 and 20 (inclusive):\n   attempts       name qualify  score\nc         2  Katherine     yes   16.5\nf         3    Michael     yes   20.0\nj         1      Jonas     yes   19.0"

In [ ]:
df[(df['score']>=15) & (df['score']<= 20)]

        name  score  attempts qualify
2  Katherine   16.5         2     yes
5    Michael   20.0         3     yes
9      Jonas   19.0         1     yes

In [ ]:
"""11. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes"""

"11. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nNumber of attempts in the examination is less than 2 and score greater than 15 :\n    name  score  attempts qualify\nj  Jonas   19.0         1     yes"

In [ ]:
df[(df['attempts']<2) & (df['score'] > 15)]

    name  score  attempts qualify
9  Jonas   19.0         1     yes

In [ ]:
"""12. Write a Pandas program to change the score in row 'd' to 11.5.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Change the score in row 'd' to 11.5:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
...
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0"""

"12. Write a Pandas program to change the score in row 'd' to 11.5.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nChange the score in row 'd' to 11.5:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\nc         2  Katherine     yes   16.5\n...\ni         2      Kevin      no    8.0\nj         1      Jonas     yes   19.0"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})
df.loc[3, 'score'] = 11.5
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James   11.5         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [ ]:
"""13. Write a Pandas program to calculate the sum of the examination attempts by the students.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


Expected Output:
Sum of the examination attempts by the students:
19"""

"13. Write a Pandas program to calculate the sum of the examination attempts by the students.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\n\nExpected Output:\nSum of the examination attempts by the students:\n19"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

sum(df['attempts'])

19

In [ ]:
"""14. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Mean score for each different student in data frame:
13.5625"""

"14. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nMean score for each different student in data frame:\n13.5625"

In [ ]:
df['score'].mean()

13.5625

In [ ]:
"""15. Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

Expected Output:
Append a new row:

Print all records after insert a new record:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
......
j         1      Jonas     yes   19.0
k         1     Suresh     yes   15.5

Delete the new row and display the original  rows:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
........
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0"""

'15. Write a Pandas program to append a new row \'k\' to data frame with given values for each column. Now delete the new row and return the original DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {\'name\': [\'Anastasia\', \'Dima\', \'Katherine\', \'James\', \'Emily\', \'Michael\', \'Matthew\', \'Laura\', \'Kevin\', \'Jonas\'],\n\'score\': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n\'attempts\': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n\'qualify\': [\'yes\', \'no\', \'yes\', \'no\', \'no\', \'yes\', \'yes\', \'no\', \'no\', \'yes\']}\nlabels = [\'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'i\', \'j\']\nValues for each column will be:\nname : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"\n\nExpected Output:\nAppend a new row:\n\nPrint all records after insert a new record:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\n......\nj         1      Jonas     yes   19.0\nk         1     Suresh     yes   15.5\n\nDelete the new row and display the original  rows:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\n........\ni         2      Kevin      no    8.0\nj         1      Jonas     yes   19.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.loc["k"] = ["Suresh", 15.5, 1, "yes"]
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

In [ ]:
"""16. Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"


Expected Output:
Orginal rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Sort the data frame first by 'name' in descending order, then by 'score' in ascending order:
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes"""

'16. Write a Pandas program to sort the DataFrame first by \'name\' in descending order, then by \'score\' in ascending order.\nSample Python dictionary data and list labels:\nexam_data = {\'name\': [\'Anastasia\', \'Dima\', \'Katherine\', \'James\', \'Emily\', \'Michael\', \'Matthew\', \'Laura\', \'Kevin\', \'Jonas\'],\n\'score\': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n\'attempts\': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n\'qualify\': [\'yes\', \'no\', \'yes\', \'no\', \'no\', \'yes\', \'yes\', \'no\', \'no\', \'yes\']}\nlabels = [\'a\', \'b\', \'c\', \'d\', \'e\', \'f\', \'g\', \'h\', \'i\', \'j\']\nValues for each column will be:\nname : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"\n\n\nExpected Output:\nOrginal rows:\n        name  score  attempts qualify\na  Anastasia   12.5         1     yes\nb       Dima    9.0         3      no\nc  Katherine   16.5         2     yes\nd      James    NaN         3      no\ne      Emily    9.0         2      no\nf    Michael   20.0         3     yes\ng    Matthew   14.5         1     yes\nh      Laura    NaN         1      no\ni      Kevin    8.0         2      no\nj      Jonas   19.0         1     yes\nSort the data frame first by \'name\' in descending order, then by \'score\' in ascending order:\n        name  score  attempts qualify\nf    Michael   20.0         3     yes\ng    Matthew   14.5         1     yes\nh      Laura    NaN         1      no\ni      Kevin    8.0         2      no\nc  Katherine   16.5         2     yes\nj      Jonas   19.0         1     yes\nd      James    NaN         3      no\ne      Emily    9.0         2      no\nb       Dima    9.0         3      no\na  Anastasia   12.5         1     yes'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.sort_values(by = ['name', 'score'], ascending = [False, True])

        name  score  attempts qualify
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
2  Katherine   16.5         2     yes
9      Jonas   19.0         1     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
1       Dima    9.0         3      no
0  Anastasia   12.5         1     yes

In [ ]:
"""17. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Replace the 'qualify' column contains the values 'yes' and 'no'  with T
rue and  False:
   attempts       name  qualify  score
a         1  Anastasia     True   12.5
b         3       Dima    False    9.0
......
i         2      Kevin    False    8.0
j         1      Jonas     True   19.0"""

"17. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nReplace the 'qualify' column contains the values 'yes' and 'no'  with T\nrue and  False:\n   attempts       name  qualify  score\na         1  Anastasia     True   12.5\nb         3       Dima    False    9.0\n......\ni         2      Kevin    False    8.0\nj         1      Jonas     True   19.0"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df['qualify'] = df['qualify'].map({'yes' : True, 'no' : False})
df

        name  score  attempts  qualify
0  Anastasia   12.5         1     True
1       Dima    9.0         3    False
2  Katherine   16.5         2     True
3      James    NaN         3    False
4      Emily    9.0         2    False
5    Michael   20.0         3     True
6    Matthew   14.5         1     True
7      Laura    NaN         1    False
8      Kevin    8.0         2    False
9      Jonas   19.0         1     True

In [ ]:
"""18. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
Change the name 'James' to \?Suresh\?:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
.......
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0"""

"18. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\nChange the name 'James' to \\?Suresh\\?:\n   attempts       name qualify  score\na         1  Anastasia     yes   12.5\nb         3       Dima      no    9.0\n.......\ni         2      Kevin      no    8.0\nj         1      Jonas     yes   19.0"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df['name'] = df['name'].replace('James' , 'Suresh')
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3     Suresh    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [ ]:
"""19. Write a Pandas program to delete the 'attempts' column from the DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


Expected Output:
Delete the 'attempts' column from the data frame:
        name qualify  score
a  Anastasia     yes   12.5
b       Dima      no    9.0
.....
i      Kevin      no    8.0
j      Jonas     yes   19.0"""

"19. Write a Pandas program to delete the 'attempts' column from the DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\n\nExpected Output:\nDelete the 'attempts' column from the data frame:\n        name qualify  score\na  Anastasia     yes   12.5\nb       Dima      no    9.0\n.....\ni      Kevin      no    8.0\nj      Jonas     yes   19.0"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.pop('attempts')
df

        name  score qualify
0  Anastasia   12.5     yes
1       Dima    9.0      no
2  Katherine   16.5     yes
3      James    NaN      no
4      Emily    9.0      no
5    Michael   20.0     yes
6    Matthew   14.5     yes
7      Laura    NaN      no
8      Kevin    8.0      no
9      Jonas   19.0     yes

In [ ]:
"""20. Write a Pandas program to insert a new column in existing DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


Expected Output:
New DataFrame after inserting the 'color' column
   attempts       name qualify  score   color
a         1  Anastasia     yes   12.5     Red
b         3       Dima      no    9.0    Blue
.......
i         2      Kevin      no    8.0   Green
j         1      Jonas     yes   19.0     Red"""

"20. Write a Pandas program to insert a new column in existing DataFrame.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\n\nExpected Output:\nNew DataFrame after inserting the 'color' column\n   attempts       name qualify  score   color\na         1  Anastasia     yes   12.5     Red\nb         3       Dima      no    9.0    Blue\n.......\ni         2      Kevin      no    8.0   Green\nj         1      Jonas     yes   19.0     Red"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df[5] = ['blue', 'blue', 'asdasd', 'blue', 'jfdfgh', 'blue', 'xcvwe', 'blue', 'awerb', 'blue']
df

        name  score  attempts qualify       5
0  Anastasia   12.5         1     yes    blue
1       Dima    9.0         3      no    blue
2  Katherine   16.5         2     yes  asdasd
3      James    NaN         3      no    blue
4      Emily    9.0         2      no  jfdfgh
5    Michael   20.0         3     yes    blue
6    Matthew   14.5         1     yes   xcvwe
7      Laura    NaN         1      no    blue
8      Kevin    8.0         2      no   awerb
9      Jonas   19.0         1     yes    blue

In [ ]:
"""21. Write a Pandas program to iterate over rows in a DataFrame.
Sample Python dictionary data and list labels:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]

Expected Output:
Anastasia 12.5
Dima 9.0
Katherine 16.5"""

"21. Write a Pandas program to iterate over rows in a DataFrame.\nSample Python dictionary data and list labels:\nexam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]\n\nExpected Output:\nAnastasia 12.5\nDima 9.0\nKatherine 16.5"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

for index, row in df.iterrows():
  print(f"{row['name']} : {row['score']}")

Anastasia : 12.5
Dima : 9.0
Katherine : 16.5
James : nan
Emily : 9.0
Michael : 20.0
Matthew : 14.5
Laura : nan
Kevin : 8.0
Jonas : 19.0

In [ ]:
"""22. Write a Pandas program to get list from DataFrame column headers.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Expected Output:
['attempts', 'name', 'qualify', 'score']"""

"22. Write a Pandas program to get list from DataFrame column headers.\nSample Python dictionary data and list labels:\nexam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\nlabels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n\nExpected Output:\n['attempts', 'name', 'qualify', 'score']"

In [ ]:
 df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

list(df.columns)

['name', 'score', 'attempts', 'qualify']

In [ ]:
"""23. Write a Pandas program to rename columns of a given DataFrame
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9"""

'23. Write a Pandas program to rename columns of a given DataFrame\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6     9\nNew DataFrame after renaming columns:\n   Column1  Column2  Column3\n0        1        4        7\n1        2        5        8\n2        3        6        9'

In [ ]:
df.rename(columns = {
    'score' : 'bababooey',
    'attempts': 'kjhgoiasdgfobayd'
})

        name  bababooey  kjhgoiasdgfobayd qualify
0  Anastasia       12.5                 1     yes
1       Dima        9.0                 3      no
2  Katherine       16.5                 2     yes
3      James        NaN                 3      no
4      Emily        9.0                 2      no
5    Michael       20.0                 3     yes
6    Matthew       14.5                 1     yes
7      Laura        NaN                 1      no
8      Kevin        8.0                 2      no
9      Jonas       19.0                 1     yes

In [ ]:
"""24. Write a Pandas program to select rows from a given DataFrame based on values in some columns.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0"""

'24. Write a Pandas program to select rows from a given DataFrame based on values in some columns.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\nRows for colum1 value == 4\n   col1  col2  col3\n1     4     5     8\n3     4     7     0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.loc[df['score']==9]

    name  score  attempts qualify
1   Dima    9.0         3      no
4  Emily    9.0         2      no

In [ ]:
"""26. Write a Pandas program to add one row in an existing DataFrame.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12"""

'26. Write a Pandas program to add one row in an existing DataFrame.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\nAfter add one row:\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\n5    10    11    12'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.loc[10] = ['Purab', 700000000000000000000, 1, "yes"]
df

         name                  score  attempts qualify
0   Anastasia                   12.5         1     yes
1        Dima                    9.0         3      no
2   Katherine                   16.5         2     yes
3       James                    NaN         3      no
4       Emily                    9.0         2      no
5     Michael                   20.0         3     yes
6     Matthew                   14.5         1     yes
7       Laura                    NaN         1      no
8       Kevin                    8.0         2      no
9       Jonas                   19.0         1     yes
10      Purab  700000000000000000000         1     yes

In [ ]:
"""29. Write a Pandas program to delete DataFrame row(s) based on given column value.
Sample data:

    Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
New DataFrame
   col1  col2  col3
0     1     4     7
2     3     6     9
3     4     7     0
4     5     8     1"""

'29. Write a Pandas program to delete DataFrame row(s) based on given column value.\nSample data:\n\n    Original DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\nNew DataFrame\n   col1  col2  col3\n0     1     4     7\n2     3     6     9\n3     4     7     0\n4     5     8     1'

In [ ]:
df = df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})
df = df[df["attempts"] != 3]
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
2  Katherine   16.5         2     yes
4      Emily    9.0         2      no
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [ ]:
"""30. Write a Pandas program to widen output display to see more columns.
Sample data:

   Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1"""

'30. Write a Pandas program to widen output display to see more columns.\nSample data:\n\n   Original DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1'

In [ ]:
pd.set_option("display.max_rows", 11)
pd.set_option("display.max_columns", 5)
pd.set_option("display.width", 10)

df

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
2,Katherine,16.5,2,yes
4,Emily,9.0,2,no
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""31. Write a Pandas program to select a row of series/dataframe by given integer index.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Index-2: Details
   col1  col2  col3
2     3     6     9"""

'31. Write a Pandas program to select a row of series/dataframe by given integer index.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\nIndex-2: Details\n   col1  col2  col3\n2     3     6     9'

In [ ]:
df.iloc[[2]]

,name,score,attempts,qualify
4,Emily,9.0,2,no

In [ ]:
"""32. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.
Sample data:

Original DataFrame

   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0"""

"32. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.\nSample data:\n\nOriginal DataFrame\n\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n.....\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nNew DataFrame replacing all NaN with 0:\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n.....\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0"

In [ ]:
df.fillna(0)

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
2,Katherine,16.5,2,yes
4,Emily,9.0,2,no
6,Matthew,14.5,1,yes
7,Laura,0.0,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""33. Write a Pandas program to convert index in a column of the given dataframe.
Sample data:

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
....
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

After converting index in a column:
   index  attempts       name qualify  score
0      0         1  Anastasia     yes   12.5
1      1         3       Dima      no    9.0
2      2         2  Katherine     yes   16.5
....
8      8         2      Kevin      no    8.0
9      9         1      Jonas     yes   19.0

Hiding index:
index  attempts       name qualify  score
    0         1  Anastasia     yes   12.5
    1         3       Dima      no    9.0
    2         2  Katherine     yes   16.5
 .....
    8         2      Kevin      no    8.0
    9         1      Jonas     yes   19.0"""

'33. Write a Pandas program to convert index in a column of the given dataframe.\nSample data:\n\nOriginal DataFrame\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n....\n7         1      Laura      no    NaN\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nAfter converting index in a column:\n   index  attempts       name qualify  score\n0      0         1  Anastasia     yes   12.5\n1      1         3       Dima      no    9.0\n2      2         2  Katherine     yes   16.5\n....\n8      8         2      Kevin      no    8.0\n9      9         1      Jonas     yes   19.0\n\nHiding index:\nindex  attempts       name qualify  score\n    0         1  Anastasia     yes   12.5\n    1         3       Dima      no    9.0\n    2         2  Katherine     yes   16.5\n .....\n    8         2      Kevin      no    8.0\n    9         1      Jonas     yes   19.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.reset_index(level=0, inplace = True)
df

,index,name,score,attempts,qualify
0,0,Anastasia,12.5,1,yes
1,1,Dima,9.0,3,no
2,2,Katherine,16.5,2,yes
3,3,James,NaN,3,no
4,4,Emily,9.0,2,no
5,5,Michael,20.0,3,yes
6,6,Matthew,14.5,1,yes
7,7,Laura,NaN,1,no
8,8,Kevin,8.0,2,no
9,9,Jonas,19.0,1,yes

In [ ]:
"""34. Write a Pandas program to set a given value for particular cell in  DataFrame using index value.
Sample data:

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
......
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Set a given value for particular cell in the DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
......
8         2      Kevin      no   10.2
9         1      Jonas     yes   19.0"""

'34. Write a Pandas program to set a given value for particular cell in  DataFrame using index value.\nSample data:\n\nOriginal DataFrame\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n......\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nSet a given value for particular cell in the DataFrame\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n......\n8         2      Kevin      no   10.2\n9         1      Jonas     yes   19.0'

In [ ]:
idf = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

#df.set_value(2, "score", 10)
df

,index,name,score,attempts,qualify
0,0,Anastasia,12.5,1,yes
1,1,Dima,9.0,3,no
2,2,Katherine,16.5,2,yes
3,3,James,NaN,3,no
4,4,Emily,9.0,2,no
5,5,Michael,20.0,3,yes
6,6,Matthew,14.5,1,yes
7,7,Laura,NaN,1,no
8,8,Kevin,8.0,2,no
9,9,Jonas,19.0,1,yes

In [ ]:
"""35. Write a Pandas program to count the NaN values in one or more columns in DataFrame.
Sample data:

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Number of NaN values in one or more columns:"""

'35. Write a Pandas program to count the NaN values in one or more columns in DataFrame.\nSample data:\n\nOriginal DataFrame\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n3         3      James      no    NaN\n4         2      Emily      no    9.0\n5         3    Michael     yes   20.0\n6         1    Matthew     yes   14.5\n7         1      Laura      no    NaN\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\nNumber of NaN values in one or more columns:'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

print(df.isnull().sum().sum())

2

In [ ]:
"""36. Write a Pandas program to drop a list of rows from a specified DataFrame.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0"""

'36. Write a Pandas program to drop a list of rows from a specified DataFrame.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n2     3     6     9\n3     4     7     0\n4     5     8     1\nNew DataFrame after removing 2nd & 4th rows:\n   col1  col2  col3\n0     1     4     7\n1     4     5     8\n3     4     7     0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

range = df.index[3:]
df.drop(range)

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes

In [ ]:
"""37. Write a Pandas program to reset index in a given DataFrame.
Sample data:

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

After removing first and second rows
   attempts       name qualify  score
2         2  Katherine     yes   16.5
3         3      James      no    NaN
....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Reset the Index:

   index  attempts       name qualify  score
0      2         2  Katherine     yes   16.5
1      3         3      James      no    NaN
2      4         2      Emily      no    9.0
3      5         3    Michael     yes   20.0
4      6         1    Matthew     yes   14.5
5      7         1      Laura      no    NaN
6      8         2      Kevin      no    8.0
7      9         1      Jonas     yes   19.0"""

'37. Write a Pandas program to reset index in a given DataFrame.\nSample data:\n\nOriginal DataFrame\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n.....\n7         1      Laura      no    NaN\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nAfter removing first and second rows\n   attempts       name qualify  score\n2         2  Katherine     yes   16.5\n3         3      James      no    NaN\n....\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nReset the Index:\n\n   index  attempts       name qualify  score\n0      2         2  Katherine     yes   16.5\n1      3         3      James      no    NaN\n2      4         2      Emily      no    9.0\n3      5         3    Michael     yes   20.0\n4      6         1    Matthew     yes   14.5\n5      7         1      Laura      no    NaN\n6      8         2      Kevin      no    8.0\n7      9         1      Jonas     yes   19.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

range = df.index[:2]
df.drop(range, inplace=True)
df.reset_index(level = 0, inplace = True)
df

,index,name,score,attempts,qualify
0,2,Katherine,16.5,2,yes
1,3,James,NaN,3,no
2,4,Emily,9.0,2,no
3,5,Michael,20.0,3,yes
4,6,Matthew,14.5,1,yes
5,7,Laura,NaN,1,no
6,8,Kevin,8.0,2,no
7,9,Jonas,19.0,1,yes

In [ ]:
"""38. Write a Pandas program to divide a DataFrame in a given ratio.
Sample data:

Original DataFrame:
          0         1
0  0.316147 -0.767359
1 -0.813410 -2.522672
2  0.869615  1.194704
.....
7 -0.726346 -0.535147
8 -1.350726  0.563117
9  1.051666 -0.441533

70% of the said DataFrame:
          0         1
8 -1.350726  0.563117
2  0.869615  1.194704
.....
1 -0.813410 -2.522672
0  0.316147 -0.767359

30% of the said DataFrame:
          0         1
4 -0.341126  0.518266
7 -0.726346 -0.535147
9  1.051666 -0.441533"""

'38. Write a Pandas program to divide a DataFrame in a given ratio.\nSample data:\n\nOriginal DataFrame:\n          0         1\n0  0.316147 -0.767359\n1 -0.813410 -2.522672\n2  0.869615  1.194704\n.....\n7 -0.726346 -0.535147\n8 -1.350726  0.563117\n9  1.051666 -0.441533\n\n70% of the said DataFrame:\n          0         1\n8 -1.350726  0.563117\n2  0.869615  1.194704\n.....\n1 -0.813410 -2.522672\n0  0.316147 -0.767359\n\n30% of the said DataFrame:\n          0         1\n4 -0.341126  0.518266\n7 -0.726346 -0.535147\n9  1.051666 -0.441533'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

dropthispls = df.sample(frac = 0.7, random_state=10)
thirtyleft = df.drop(dropthispls.index)
thirtyleft

,name,score,attempts,qualify
4,Emily,9.0,2,no
7,Laura,NaN,1,no
9,Jonas,19.0,1,yes

In [ ]:
"""39. Write a Pandas program to combining two series into a DataFrame.
Sample data:

Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       10
1       20
2      php
3    30.12
4       40
dtype: object
New DataFrame combining two series:
        0      1
0     100     10
1     200     20
2  python    php
3  300.12  30.12
4     400     40"""

'39. Write a Pandas program to combining two series into a DataFrame.\nSample data:\n\nData Series:\n0       100\n1       200\n2    python\n3    300.12\n4       400\ndtype: object\n0       10\n1       20\n2      php\n3    30.12\n4       40\ndtype: object\nNew DataFrame combining two series:\n        0      1\n0     100     10\n1     200     20\n2  python    php\n3  300.12  30.12\n4     400     40'

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([6, 7, 8, 9, 10])
df = pd.concat([ser1, ser2], axis=0)
df

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [ ]:
"""40. Write a Pandas program to shuffle a given DataFrame rows.
Sample data:

Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
....
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

New DataFrame:
   attempts       name qualify  score
5         3    Michael     yes   20.0
0         1  Anastasia     yes   12.5
....
4         2      Emily      no    9.0
8         2      Kevin      no    8.0
2         2  Katherine     yes   16.5"""

'40. Write a Pandas program to shuffle a given DataFrame rows.\nSample data:\n\nOriginal DataFrame:\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n2         2  Katherine     yes   16.5\n....\n7         1      Laura      no    NaN\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nNew DataFrame:\n   attempts       name qualify  score\n5         3    Michael     yes   20.0\n0         1  Anastasia     yes   12.5\n....\n4         2      Emily      no    9.0\n8         2      Kevin      no    8.0\n2         2  Katherine     yes   16.5'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.sample(frac = 1)

,name,score,attempts,qualify
4,Emily,9.0,2,no
0,Anastasia,12.5,1,yes
7,Laura,NaN,1,no
9,Jonas,19.0,1,yes
2,Katherine,16.5,2,yes
3,James,NaN,3,no
5,Michael,20.0,3,yes
8,Kevin,8.0,2,no
6,Matthew,14.5,1,yes
1,Dima,9.0,3,no

In [ ]:
"""41. Write a Pandas program to convert DataFrame column type from string to datetime.

Sample data:

String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object
Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13"""

'41. Write a Pandas program to convert DataFrame column type from string to datetime.\n\nSample data:\n\nString Date:\n0    3/11/2000\n1    3/12/2000\n2    3/13/2000\ndtype: object\nOriginal DataFrame (string to datetime):\n           0\n0 2000-03-11\n1 2000-03-12\n2 2000-03-13'

In [ ]:
ser = pd.Series(["3/11/2000", "3/12/2000", "3/13/2000"])

df = pd.to_datetime(ser)

dfn = pd.DataFrame(df)
dfn

           0
0 2000-03-11
1 2000-03-12
2 2000-03-13

In [ ]:
"""42. Write a Pandas program to rename a specific column name in a given DataFrame.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming second column:
   col1  Column2  col3
0     1        4     7
1     2        5     8
2     3        6     9"""

'42. Write a Pandas program to rename a specific column name in a given DataFrame.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6     9\nNew DataFrame after renaming second column:\n   col1  Column2  col3\n0     1        4     7\n1     2        5     8\n2     3        6     9'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df = df.rename(columns = {"score": "Score"})
df

,name,Score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""43. Write a Pandas program to get a list of a specified column of a DataFrame.
Sample data:

Powered by
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
Col2 of the DataFrame to list:
[4, 5, 6]"""

'43. Write a Pandas program to get a list of a specified column of a DataFrame.\nSample data:\n\nPowered by\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6     9\nCol2 of the DataFrame to list:\n[4, 5, 6]'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df["score"].tolist()

[12.5, 9.0, 16.5, nan, 9.0, 20.0, 14.5, nan, 8.0, 19.0]

In [ ]:
"""44. Write a Pandas program to create a DataFrame from a Numpy array and specify the index column and column headers.

Sample Output:
         Column1  Column2  Column3
Index1         0      0.0      0.0
Index2         0      0.0      0.0
Index3         0      0.0      0.0
.........
Index12        0      0.0      0.0
Index13        0      0.0      0.0
Index14        0      0.0      0.0
Index15        0      0.0      0.0"""

'44. Write a Pandas program to create a DataFrame from a Numpy array and specify the index column and column headers.\n\nSample Output:\n         Column1  Column2  Column3\nIndex1         0      0.0      0.0\nIndex2         0      0.0      0.0\nIndex3         0      0.0      0.0\n.........\nIndex12        0      0.0      0.0\nIndex13        0      0.0      0.0\nIndex14        0      0.0      0.0\nIndex15        0      0.0      0.0'

In [ ]:
dtype = [("column1", "int32"), ("column2", "str")]
nparray = np.zeros(2, dtype = dtype)

df = pd.DataFrame(nparray)
df

,column1,column2
0,0,
1,0,

In [ ]:
"""45. Write a Pandas program to find the row for where the value of a given column is maximum.
Sample Output:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2"""

'45. Write a Pandas program to find the row for where the value of a given column is maximum.\nSample Output:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6    12\n3     4     9     1\n4     7     5    11\nRow where col1 has maximum value:\n4\nRow where col2 has maximum value:\n3\nRow where col3 has maximum value:\n2'

In [ ]:
df = pd.DataFrame({'col1': [1, 2, 3, 4, 7],
                   'col2': [4, 5, 6, 9, 5],
                   'col3': [7, 8, 12, 1, 11]})

df['col1'].argmax()

4

In [ ]:
"""46. Write a Pandas program to check whether a given column is present in a DataFrame or not.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Col4 is not present in DataFrame.
Col1 is present in DataFrame."""

'46. Write a Pandas program to check whether a given column is present in a DataFrame or not.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6    12\n3     4     9     1\n4     7     5    11\nCol4 is not present in DataFrame.\nCol1 is present in DataFrame.'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

print("score" in df.columns)

True

In [ ]:
"""47. Write a Pandas program to get the specified row value of a given DataFrame.
Sample data:

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Value of Row
col1    1
col2    4
col3    7
Name: 0, dtype: int64
Value of Row4
col1    4
col2    9
col3    1
Name: 3, dtype: int64"""

'47. Write a Pandas program to get the specified row value of a given DataFrame.\nSample data:\n\nOriginal DataFrame\n   col1  col2  col3\n0     1     4     7\n1     2     5     8\n2     3     6    12\n3     4     9     1\n4     7     5    11\nValue of Row\ncol1    1\ncol2    4\ncol3    7\nName: 0, dtype: int64\nValue of Row4\ncol1    4\ncol2    9\ncol3    1\nName: 3, dtype: int64'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.iloc[4]

name        Emily
score         9.0
attempts        2
qualify        no
Name: 4, dtype: object

In [ ]:
"""48. Write a Pandas program to get the datatypes of columns of a DataFrame.
Sample data:

Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
.......
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object"""

'48. Write a Pandas program to get the datatypes of columns of a DataFrame.\nSample data:\n\nOriginal DataFrame:\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n.......\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\nData types of the columns of the said DataFrame:\nattempts      int64\nname         object\nqualify      object\nscore       float64\ndtype: object'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.dtypes

name         object
score       float64
attempts      int64
qualify      object
dtype: object

In [ ]:
"""49. Write a Pandas program to append data to an empty DataFrame.
Sample data:

Original DataFrame:
After appending some data:
   col1  col2
0     0     0
1     1     1
2     2     2"""

'49. Write a Pandas program to append data to an empty DataFrame.\nSample data:\n\nOriginal DataFrame:\nAfter appending some data:\n   col1  col2\n0     0     0\n1     1     1\n2     2     2'

In [ ]:
"""df = pd.DataFrame({"baba" : [],
                   "booey" : []})

appendabledataframethatiwanttoaddtotheoldone = pd.DataFrame({"baba" : range(2),
          "booey" : range(2)})
df.append(appendabledataframethatiwanttoaddtotheoldone)
df"""

'df = pd.DataFrame({"baba" : [],\n                   "booey" : []})\n\nappendabledataframethatiwanttoaddtotheoldone = pd.DataFrame({"baba" : range(2),\n          "booey" : range(2)})\ndf.append(appendabledataframethatiwanttoaddtotheoldone)\ndf'

In [ ]:
"""50. Write a Pandas program to sort a given DataFrame by two or more columns.
Sample data:

Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
........
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Sort the above DataFrame on attempts, name:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
9         1      Jonas     yes   19.0
7         1      Laura      no    NaN
6         1    Matthew     yes   14.5
4         2      Emily      no    9.0
2         2  Katherine     yes   16.5
8         2      Kevin      no    8.0
1         3       Dima      no    9.0
3         3      James      no    NaN
5         3    Michael     yes   20.0"""

'50. Write a Pandas program to sort a given DataFrame by two or more columns.\nSample data:\n\nOriginal DataFrame:\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n1         3       Dima      no    9.0\n........\n8         2      Kevin      no    8.0\n9         1      Jonas     yes   19.0\n\nSort the above DataFrame on attempts, name:\n   attempts       name qualify  score\n0         1  Anastasia     yes   12.5\n9         1      Jonas     yes   19.0\n7         1      Laura      no    NaN\n6         1    Matthew     yes   14.5\n4         2      Emily      no    9.0\n2         2  Katherine     yes   16.5\n8         2      Kevin      no    8.0\n1         3       Dima      no    9.0\n3         3      James      no    NaN\n5         3    Michael     yes   20.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.sort_values(["attempts", "name"], ascending = [True, True])

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
9,Jonas,19.0,1,yes
7,Laura,NaN,1,no
6,Matthew,14.5,1,yes
4,Emily,9.0,2,no
2,Katherine,16.5,2,yes
8,Kevin,8.0,2,no
1,Dima,9.0,3,no
3,James,NaN,3,no
5,Michael,20.0,3,yes

In [ ]:
"""51. Write a Pandas program to convert the datatype of a given column (floats to ints).
Sample data:
Original DataFrame:
attempts name qualify score
0 1 Anastasia yes 12.50
1 3 Dima no 9.10
......
8 2 Kevin no 8.80
9 1 Jonas yes 19.13
Data types of the columns of the said DataFrame:
attempts int64
name object
qualify object
score float64
dtype: object
Now change the Data type of 'score' column from float to int:
attempts name qualify score
0 1 Anastasia yes 12
1 3 Dima no 9
2 2 Katherine yes 16
3 3 James no 12
4 2 Emily no 9
5 3 Michael yes 20
6 1 Matthew yes 14
7 1 Laura no 11
8 2 Kevin no 8
9 1 Jonas yes 19
Data types of the columns of the DataFrame now:
attempts int64
name object
qualify object
score int64
dtype: object"""

"51. Write a Pandas program to convert the datatype of a given column (floats to ints).\nSample data:\nOriginal DataFrame:\nattempts name qualify score\n0 1 Anastasia yes 12.50\n1 3 Dima no 9.10\n......\n8 2 Kevin no 8.80\n9 1 Jonas yes 19.13\nData types of the columns of the said DataFrame:\nattempts int64\nname object\nqualify object\nscore float64\ndtype: object\nNow change the Data type of 'score' column from float to int:\nattempts name qualify score\n0 1 Anastasia yes 12\n1 3 Dima no 9\n2 2 Katherine yes 16\n3 3 James no 12\n4 2 Emily no 9\n5 3 Michael yes 20\n6 1 Matthew yes 14\n7 1 Laura no 11\n8 2 Kevin no 8\n9 1 Jonas yes 19\nData types of the columns of the DataFrame now:\nattempts int64\nname object\nqualify object\nscore int64\ndtype: object"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, 13, 9, 20, 14.5, 12, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.score = df.score.astype(int)
df.dtypes

name        object
score        int64
attempts     int64
qualify     object
dtype: object

In [ ]:
"""52. Write a Pandas program to remove infinite values from a given DataFrame.
Sample data:
Original DataFrame:
0
0 1000.000000
1 2000.000000
2 3000.000000
3 -4000.000000
4 inf
5 -inf
Removing infinite values:
0
0 1000.0
1 2000.0
2 3000.0
3 -4000.0
4 NaN
5 NaN"""

'52. Write a Pandas program to remove infinite values from a given DataFrame.\nSample data:\nOriginal DataFrame:\n0\n0 1000.000000\n1 2000.000000\n2 3000.000000\n3 -4000.000000\n4 inf\n5 -inf\nRemoving infinite values:\n0\n0 1000.0\n1 2000.0\n2 3000.0\n3 -4000.0\n4 NaN\n5 NaN'

In [ ]:
data = {'col1': [-np.inf, 2, 3, 4, 7],
        'col2': [4, 5, np.inf, 9, 5],
        'col3': [7, 8, 12, 1, np.inf]}

df = pd.DataFrame(data)


df.replace([np.inf, -np.inf], ["used to be POSITIVE INFITY :O", "used to be NEGATIVE INFITIY :O"])

,col1,col2,col3
0,used to be NEGATIVE INFITIY :O,4.0,7.0
1,2.0,5.0,8.0
2,3.0,used to be POSITIVE INFITY :O,12.0
3,4.0,9.0,1.0
4,7.0,5.0,used to be POSITIVE INFITY :O

In [ ]:
"""53. Write a Pandas program to insert a given column at a specific column index in a DataFrame.
Sample data:
Original DataFrame
col2 col3
0 4 7
1 5 8
2 6 12
3 9 1
4 5 11
New DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 12
3 4 9 1
4 7 5 11"""

'53. Write a Pandas program to insert a given column at a specific column index in a DataFrame.\nSample data:\nOriginal DataFrame\ncol2 col3\n0 4 7\n1 5 8\n2 6 12\n3 9 1\n4 5 11\nNew DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 8\n2 3 6 12\n3 4 9 1\n4 7 5 11'

In [ ]:
data = {'col1': [1, 2, 3, 4, 7],
        'col2': [4, 5, 6, 9, 5],
        'col3': [7, 8, 12, 1, 11]}

df = pd.DataFrame(data)

df.insert(loc=0, column="The incredibly amazing column that was added via this very code cell using the .insert() function that was probably written by an extremely experienced programmer that might have dropped out of college", value = [1, 3, 5, 7, "guess what:9"])

df

,The incredibly amazing column that was added via this very code cell using the .insert() function that was probably written by an extremely experienced programmer that might have dropped out of college,col1,col2,col3
0,1,1,4,7
1,3,2,5,8
2,5,3,6,12
3,7,4,9,1
4,guess what:9,7,5,11

In [ ]:
"""54. Write a Pandas program to convert a given list of lists into a Dataframe.
Sample data:
Original list of lists:
[[2, 4], [1, 3]]
New DataFrame
col1 col2
0 2 4
1 1 3"""

'54. Write a Pandas program to convert a given list of lists into a Dataframe.\nSample data:\nOriginal list of lists:\n[[2, 4], [1, 3]]\nNew DataFrame\ncol1 col2\n0 2 4\n1 1 3'

In [ ]:
listthatihavecreatedandhasnothingtodowiththepredefinedword = [[1, 3], [5, 7]]

dictthatwillbecomeadataframe = {}
"""
z=0
for i in listthatihavecreatedandhasnothingtodowiththepredefinedword:
  z+=1
  dictthatwillbecomeadataframe.update({
      f"col{z}" : i
  })
"""
df = pd.DataFrame(listthatihavecreatedandhasnothingtodowiththepredefinedword, columns = ["col1", "col2"])
df

,col1,col2
0,1,3
1,5,7

In [ ]:
"""55. Write a Pandas program to group by the first column and get second column as lists in rows.
Sample data:
Original DataFrame
col1 col2
0 C1 1
1 C1 2
2 C2 3
3 C2 3
4 C2 4
5 C3 6
6 C2 5"""

'55. Write a Pandas program to group by the first column and get second column as lists in rows.\nSample data:\nOriginal DataFrame\ncol1 col2\n0 C1 1\n1 C1 2\n2 C2 3\n3 C2 3\n4 C2 4\n5 C3 6\n6 C2 5'

In [ ]:
df = pd.DataFrame(
{'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

#df.groupby("score")["name"].apply(list)

def reverse(s):
  return s[::-1]

df['name'] = df["name"].apply(reverse)
df

,name,score,attempts,qualify
0,aisatsanA,12.5,1,yes
1,amiD,9.0,3,no
2,enirehtaK,16.5,2,yes
3,semaJ,NaN,3,no
4,ylimE,9.0,2,no
5,leahciM,20.0,3,yes
6,wehttaM,14.5,1,yes
7,aruaL,NaN,1,no
8,niveK,8.0,2,no
9,sanoJ,19.0,1,yes

In [ ]:
"""56. Write a Pandas program to get column index from column name of a given DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 12
3 4 9 1
4 7 5 11
Index of 'col2'
1"""

"56. Write a Pandas program to get column index from column name of a given DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 8\n2 3 6 12\n3 4 9 1\n4 7 5 11\nIndex of 'col2'\n1"

In [ ]:
df.columns.get_loc('qualify')

3

In [ ]:
"""57. Write a Pandas program to count number of columns of a DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 12
3 4 9 1
4 7 5 11
Number of columns:
3"""

'57. Write a Pandas program to count number of columns of a DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 8\n2 3 6 12\n3 4 9 1\n4 7 5 11\nNumber of columns:\n3'

In [ ]:
len(df.columns)

4

In [ ]:
"""58. Write a Pandas program to select all columns, except one given column in a DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 8
2 3 6 12
3 4 9 1
4 7 5 11
All columns except 'col3':
col1 col2
0 1 4
1 2 5
2 3 6
3 4 9
4 7 5"""

"58. Write a Pandas program to select all columns, except one given column in a DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 8\n2 3 6 12\n3 4 9 1\n4 7 5 11\nAll columns except 'col3':\ncol1 col2\n0 1 4\n1 2 5\n2 3 6\n3 4 9\n4 7 5"

In [ ]:
df.loc[:, df.columns != 'name']

,score,attempts,qualify
0,12.5,1,yes
1,9.0,3,no
2,16.5,2,yes
3,NaN,3,no
4,9.0,2,no
5,20.0,3,yes
6,14.5,1,yes
7,NaN,1,no
8,8.0,2,no
9,19.0,1,yes

In [ ]:
df.head(3)

,name,score,attempts,qualify
0,aisatsanA,12.5,1,yes
1,amiD,9.0,3,no
2,enirehtaK,16.5,2,yes

In [ ]:
"""60. Write a Pandas program to get last n records of a DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
Last 3 rows of the said DataFrame':
col1 col2 col3
3 4 9 12
4 7 5 1
5 11 0 11"""

"60. Write a Pandas program to get last n records of a DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\nLast 3 rows of the said DataFrame':\ncol1 col2 col3\n3 4 9 12\n4 7 5 1\n5 11 0 11"

In [ ]:
df.tail(3)

,name,score,attempts,qualify
7,aruaL,NaN,1,no
8,niveK,8.0,2,no
9,sanoJ,19.0,1,yes

In [ ]:
"""61. Write a Pandas program to get topmost n records within each group of a DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
topmost n records within each group of a DataFrame:
col1 col2 col3
5 11 0 11
4 7 5 1
3 4 9 12
col1 col2 col3
3 4 9 12
2 3 6 8
1 2 5 5
4 7 5 1
col1 col2 col3
3 4 9 12
5 11 0 11
2 3 6 8"""

'61. Write a Pandas program to get topmost n records within each group of a DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\ntopmost n records within each group of a DataFrame:\ncol1 col2 col3\n5 11 0 11\n4 7 5 1\n3 4 9 12\ncol1 col2 col3\n3 4 9 12\n2 3 6 8\n1 2 5 5\n4 7 5 1\ncol1 col2 col3\n3 4 9 12\n5 11 0 11\n2 3 6 8'

In [ ]:
data = {'col1': [1, 2, 3, 4, 7],
        'col2': [4, 5, 6, 9, 5],
        'col3': [7, 8, 12, 1, 11]}

df = pd.DataFrame(data)

df.nlargest(3, 'col3')

,col1,col2,col3
2,3,6,12
4,7,5,11
1,2,5,8

In [ ]:
"""62. Write a Pandas program to remove first n rows of a given DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
After removing first 3 rows of the said DataFrame:
col1 col2 col3
3 4 9 12
4 7 5 1
5 11 0 11"""

'62. Write a Pandas program to remove first n rows of a given DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\nAfter removing first 3 rows of the said DataFrame:\ncol1 col2 col3\n3 4 9 12\n4 7 5 1\n5 11 0 11'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df = df.iloc[3:]
df

,name,score,attempts,qualify
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""63. Write a Pandas program to remove last n rows of a given DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
After removing last 3 rows of the said DataFrame:
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8"""

'63. Write a Pandas program to remove last n rows of a given DataFrame.\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\nAfter removing last 3 rows of the said DataFrame:\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df = df.iloc[:(df.shape[0])-2]
df

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no

In [ ]:
"""64. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83
Add prefix:
A_W A_X A_Y A_Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83
Add suffix:
W_1 X_1 Y_1 Z_1
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83"""

'64. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.\nSample Output:\nOriginal DataFrame\nW X Y Z\n0 68 78 84 86\n1 75 85 94 97\n2 86 96 89 96\n3 80 80 83 72\n4 66 86 86 83\nAdd prefix:\nA_W A_X A_Y A_Z\n0 68 78 84 86\n1 75 85 94 97\n2 86 96 89 96\n3 80 80 83 72\n4 66 86 86 83\nAdd suffix:\nW_1 X_1 Y_1 Z_1\n0 68 78 84 86\n1 75 85 94 97\n2 86 96 89 96\n3 80 80 83 72\n4 66 86 86 83'

In [ ]:
df = df.add_prefix('A_')
df = df.add_suffix('_1')
df

,A_name_1,A_score_1,A_attempts_1,A_qualify_1
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no

In [ ]:
"""65. Write a Pandas program to reverse order (rows, columns) of a given DataFrame.
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83
Reverse column order:
Z Y X W
0 86 84 78 68
1 97 94 85 75
2 96 89 96 86
3 72 83 80 80
4 83 86 86 66
Reverse row order:
W X Y Z
4 66 86 86 83
3 80 80 83 72
2 86 96 89 96
1 75 85 94 97
0 68 78 84 86
Reverse row order and reset index:
W X Y Z
0 66 86 86 83
1 80 80 83 72
2 86 96 89 96
3 75 85 94 97
4 68 78 84 86"""

'65. Write a Pandas program to reverse order (rows, columns) of a given DataFrame.\nSample Output:\nOriginal DataFrame\nW X Y Z\n0 68 78 84 86\n1 75 85 94 97\n2 86 96 89 96\n3 80 80 83 72\n4 66 86 86 83\nReverse column order:\nZ Y X W\n0 86 84 78 68\n1 97 94 85 75\n2 96 89 96 86\n3 72 83 80 80\n4 83 86 86 66\nReverse row order:\nW X Y Z\n4 66 86 86 83\n3 80 80 83 72\n2 86 96 89 96\n1 75 85 94 97\n0 68 78 84 86\nReverse row order and reset index:\nW X Y Z\n0 66 86 86 83\n1 80 80 83 72\n2 86 96 89 96\n3 75 85 94 97\n4 68 78 84 86'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

(df.iloc[:, ::-1])

,qualify,attempts,score,name
0,yes,1,12.5,Anastasia
1,no,3,9.0,Dima
2,yes,2,16.5,Katherine
3,no,3,NaN,James
4,no,2,9.0,Emily
5,yes,3,20.0,Michael
6,yes,1,14.5,Matthew
7,no,1,NaN,Laura
8,no,2,8.0,Kevin
9,yes,1,19.0,Jonas

In [ ]:
(df.iloc[::-1])

,name,score,attempts,qualify
9,Jonas,19.0,1,yes
8,Kevin,8.0,2,no
7,Laura,NaN,1,no
6,Matthew,14.5,1,yes
5,Michael,20.0,3,yes
4,Emily,9.0,2,no
3,James,NaN,3,no
2,Katherine,16.5,2,yes
1,Dima,9.0,3,no
0,Anastasia,12.5,1,yes

In [ ]:
(df.iloc[::-1, ::-1])
df.reset_index(drop=True)

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""66. Write a Pandas program to select columns by data type of a given DataFrame.
Sample Output:
Original DataFrame
name date_of_birth age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
Select numerical columns
age
0 18.5
1 21.2
2 22.5
3 22.0
4 23.0
Select string columns
name date_of_birth
0 Alberto Franco 17/05/2002
1 Gino Mcneill 16/02/1999
2 Ryan Parkes 25/09/1998
3 Eesha Hinton 11/05/2002
4 Syed Wharton 15/09/1997"""

'66. Write a Pandas program to select columns by data type of a given DataFrame.\nSample Output:\nOriginal DataFrame\nname date_of_birth age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\nSelect numerical columns\nage\n0 18.5\n1 21.2\n2 22.5\n3 22.0\n4 23.0\nSelect string columns\nname date_of_birth\n0 Alberto Franco 17/05/2002\n1 Gino Mcneill 16/02/1999\n2 Ryan Parkes 25/09/1998\n3 Eesha Hinton 11/05/2002\n4 Syed Wharton 15/09/1997'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df.select_dtypes(include='float64')

   score
0   12.5
1    9.0
2   16.5
3    NaN
4    9.0
5   20.0
6   14.5
7    NaN
8    8.0
9   19.0

In [ ]:
"""67. Write a Pandas program to split a given DataFrame into two random subsets.
Sample Output:
Original Dataframe and shape:
name date_of_birth age
0 Alberto Franco 17/05/2002 18
1 Gino Mcneill 16/02/1999 21
2 Ryan Parkes 25/09/1998 22
3 Eesha Hinton 11/05/2002 22
4 Syed Wharton 15/09/1997 23
(5, 3)
Subset-1 and shape:
name date_of_birth age
1 Gino Mcneill 16/02/1999 21
4 Syed Wharton 15/09/1997 23
2 Ryan Parkes 25/09/1998 22
(3, 3)
Subset-2 and shape:
name date_of_birth age
0 Alberto Franco 17/05/2002 18
3 Eesha Hinton 11/05/2002 22
(2, 3)"""

'67. Write a Pandas program to split a given DataFrame into two random subsets.\nSample Output:\nOriginal Dataframe and shape:\nname date_of_birth age\n0 Alberto Franco 17/05/2002 18\n1 Gino Mcneill 16/02/1999 21\n2 Ryan Parkes 25/09/1998 22\n3 Eesha Hinton 11/05/2002 22\n4 Syed Wharton 15/09/1997 23\n(5, 3)\nSubset-1 and shape:\nname date_of_birth age\n1 Gino Mcneill 16/02/1999 21\n4 Syed Wharton 15/09/1997 23\n2 Ryan Parkes 25/09/1998 22\n(3, 3)\nSubset-2 and shape:\nname date_of_birth age\n0 Alberto Franco 17/05/2002 18\n3 Eesha Hinton 11/05/2002 22\n(2, 3)'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df1 = df.sample(frac=0.5)
df1

,name,score,attempts,qualify
4,Emily,9.0,2,no
2,Katherine,16.5,2,yes
7,Laura,NaN,1,no
0,Anastasia,12.5,1,yes
5,Michael,20.0,3,yes

In [ ]:
df2 = df.drop(df1.index)
df2

,name,score,attempts,qualify
1,Dima,9.0,3,no
3,James,NaN,3,no
6,Matthew,14.5,1,yes
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""68. Write a Pandas program to rename all columns with the same pattern of a given DataFrame.
Sample Output:
Original DataFrame
Name Date_Of_Birth Age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
Remove trailing (at the end) whitesapce and convert to lowercase of the columns name
name date_of_birth age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0"""

'68. Write a Pandas program to rename all columns with the same pattern of a given DataFrame.\nSample Output:\nOriginal DataFrame\nName Date_Of_Birth Age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\nRemove trailing (at the end) whitesapce and convert to lowercase of the columns name\nname date_of_birth age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'ScOrE': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'AtTeMpTs': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'QuAliFy': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})


df.columns = df.columns.str.lower()
df

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
5,Michael,20.0,3,yes
6,Matthew,14.5,1,yes
7,Laura,NaN,1,no
8,Kevin,8.0,2,no
9,Jonas,19.0,1,yes

In [ ]:
"""69. Write a Pandas program to merge datasets and check uniqueness.
Sample Output:
Original DataFrame:
Name Date_Of_Birth Age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
New DataFrames:
Name Date_Of_Birth Age
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
Name Date_Of_Birth Age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
"one_to_one": check if merge keys are unique in both left and right datasets:"
Name Date_Of_Birth Age
0 Eesha Hinton 11/05/2002 22.0
1 Syed Wharton 15/09/1997 23.0
"one_to_many" or "1:m": check if merge keys are unique in left dataset:
Name Date_Of_Birth Age
0 Eesha Hinton 11/05/2002 22.0
1 Syed Wharton 15/09/1997 23.0
"any_to_one" or "m:1": check if merge keys are unique in right dataset:
Name Date_Of_Birth Age
0 Eesha Hinton 11/05/2002 22.0
1 Syed Wharton 15/09/1997 23.0"""

'69. Write a Pandas program to merge datasets and check uniqueness.\nSample Output:\nOriginal DataFrame:\nName Date_Of_Birth Age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\nNew DataFrames:\nName Date_Of_Birth Age\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\nName Date_Of_Birth Age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\n"one_to_one": check if merge keys are unique in both left and right datasets:"\nName Date_Of_Birth Age\n0 Eesha Hinton 11/05/2002 22.0\n1 Syed Wharton 15/09/1997 23.0\n"one_to_many" or "1:m": check if merge keys are unique in left dataset:\nName Date_Of_Birth Age\n0 Eesha Hinton 11/05/2002 22.0\n1 Syed Wharton 15/09/1997 23.0\n"any_to_one" or "m:1": check if merge keys are unique in right dataset:\nName Date_Of_Birth Age\n0 Eesha Hinton 11/05/2002 22.0\n1 Syed Wharton 15/09/1997 23.0'

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

data = {'name': [1, 2, 3, 4, 7],
        'score': [4, 5, 6, 9, 5],
        'attempts': [7, 8, 12, 1, 11],
        'qualify' : [1, 2, 3, 4, 5]}

df1 = pd.DataFrame(data)

pd.concat([df, df1])

,name,score,attempts,qualify
0,Anastasia,12.5,1,yes
1,Dima,9.0,3,no
2,Katherine,16.5,2,yes
3,James,NaN,3,no
4,Emily,9.0,2,no
...,...,...,...,...
0,1,4.0,7,1
1,2,5.0,8,2
2,3,6.0,12,3
3,4,9.0,1,4
4,7,5.0,11,5

In [ ]:
"""70. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.
Input:
{ 'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
'Age': [18, 22, 40, 50, 80, 5] }
Output:
Age group:
0 kids
1 adult
2 elderly
3 adult
4 elderly
5 kids
Name: age_groups, dtype: category
Categories (3, object): [kids < adult < elderly]"""

"70. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.\nInput:\n{ 'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],\n'Age': [18, 22, 40, 50, 80, 5] }\nOutput:\nAge group:\n0 kids\n1 adult\n2 elderly\n3 adult\n4 elderly\n5 kids\nName: age_groups, dtype: category\nCategories (3, object): [kids < adult < elderly]"

In [ ]:
df = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, 23, 9, 20, 14.5, 75000000000000, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']})

df = pd.cut(df['score'], bins=[0, 10, 15, 30, 7500000000000000000000000], labels=['Dumb', 'Average', 'Still very dumb', '>elon musk'])
df

0            Average
1               Dumb
2    Still very dumb
3    Still very dumb
4               Dumb
5    Still very dumb
6            Average
7         >elon musk
8               Dumb
9    Still very dumb
Name: score, dtype: category
Categories (4, object): [ <
                         'Dumb' <
                         'Average' <
                         'Still very dumb' <
                         '>elon musk']

In [ ]:
"""71. Write a Pandas program to display memory usage of a given DataFrame and every column of the DataFrame.
Sample Output:
Original DataFrame:
Name Date_Of_Birth Age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Syed Wharton 15/09/1997 23.0
Global usage of memory of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
Name 5 non-null object
Date_Of_Birth 5 non-null object
Age 5 non-null float64
dtypes: float64(1), object(2)
memory usage: 801.0 bytes
None
The usage of memory of every column of the said DataFrame:
Index 80
Name 346
Date_Of_Birth 335
Age 40
dtype: int64"""

"71. Write a Pandas program to display memory usage of a given DataFrame and every column of the DataFrame.\nSample Output:\nOriginal DataFrame:\nName Date_Of_Birth Age\n0 Alberto Franco 17/05/2002 18.5\n1 Gino Mcneill 16/02/1999 21.2\n2 Ryan Parkes 25/09/1998 22.5\n3 Eesha Hinton 11/05/2002 22.0\n4 Syed Wharton 15/09/1997 23.0\nGlobal usage of memory of the DataFrame:\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 5 entries, 0 to 4\nData columns (total 3 columns):\nName 5 non-null object\nDate_Of_Birth 5 non-null object\nAge 5 non-null float64\ndtypes: float64(1), object(2)\nmemory usage: 801.0 bytes\nNone\nThe usage of memory of every column of the said DataFrame:\nIndex 80\nName 346\nDate_Of_Birth 335\nAge 40\ndtype: int64"

In [ ]:
df.memory_usage()

342

In [ ]:
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""72. Write a Pandas program to combine many given series to create a DataFrame.
Sample Output:
Original Series:
0 php
1  python
2 java
3 c#
4 c++
dtype: object
0 1
1 2
2 3
3 4
4 5
dtype: int64
Combine above series to a dataframe:
index 0
0 1  python
1 2 java
2 3 c#
3 4 c++
4 5 NaN
Using pandas concat:
0 1
0 php 1
1 python 2
2 java 3
3 c# 4
4 c++ 5
Using pandas DataFrame with a dictionary, gives a specific name to the columns:
col1 col2
0 php 1
1 python 2
2 java 3
3 c# 4
4 c++ 5"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

'72. Write a Pandas program to combine many given series to create a DataFrame.\nSample Output:\nOriginal Series:\n0 php\n1  python\n2 java\n3 c#\n4 c++\ndtype: object\n0 1\n1 2\n2 3\n3 4\n4 5\ndtype: int64\nCombine above series to a dataframe:\nindex 0\n0 1  python\n1 2 java\n2 3 c#\n3 4 c++\n4 5 NaN\nUsing pandas concat:\n0 1\n0 php 1\n1 python 2\n2 java 3\n3 c# 4\n4 c++ 5\nUsing pandas DataFrame with a dictionary, gives a specific name to the columns:\ncol1 col2\n0 php 1\n1 python 2\n2 java 3\n3 c# 4\n4 c++ 5'

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([6, 7, 8, 9, 10])
ser3 = pd.Series([4, 2, 1, 6, 3])
ser4 = pd.Series([1, 6, 2, 4, 9])

"""df = pd.concat([ser1, ser2, ser3, ser4], axis=1)
df"""

"""df = pd.DataFrame([ser1, ser2, ser3, ser4]).reset_index(drop=True)
df"""

df = pd.DataFrame({'ba' : ser1,
                   'ba2.0' : ser2,
                   'boo' : ser3,
                   'ey' : ser4})
df

,ba,ba2.0,boo,ey
0,1,6,4,1
1,2,7,2,6
2,3,8,1,2
3,4,9,6,4
4,5,10,3,9

In [ ]:
"""73. Write a Pandas program to create DataFrames that contains random values, contains missing values, contains datetime values and contains mixed values.
Sample Output:
DataFrame: Contains random values:
A B C D
Dog2w4Dv4l 0.591058 1.883454 -1.608613 -0.502516
kV7mfdFcF9 0.629642 -0.474377 0.567357 1.658445
.......
DataFrame: Contains missing values:
A B C D
i6i6Xn9l9c -0.299335 0.410871 -0.431840 -0.302177
OGo5KNNYNJ -0.174594 -1.366146 0.435063 -2.779446
u0mG9q1L7C 1.019094 -0.061077 -1.138138 -0.218460
RNJGqpci4o -0.380815 0.189970 -2.148521 -1.163589
vXIcxItZ1D NaN -0.079448 0.604777 0.065290
........
DataFrame: Contains datetime values:
A B C D
2000-01-03 0.665402 0.860808 -0.180986 -0.970889
2000-01-04 -1.511533 0.487539 -0.710355 -0.807816
2000-01-05 -0.773294 0.197918 -1.214035 1.049529
2000-01-06 -1.074894 1.774147 -0.620025 0.740779
.......
DataFrame: Contains mixed values:
A B C D
0 0.0 0.0 foo1 2009-01-01
1 1.0 1.0 foo2 2009-01-02
2 2.0 0.0 foo3 2009-01-05
3 3.0 1.0 foo4 2009-01-06
4 4.0 0.0 foo5 2009-01-07"""

'73. Write a Pandas program to create DataFrames that contains random values, contains missing values, contains datetime values and contains mixed values.\nSample Output:\nDataFrame: Contains random values:\nA B C D\nDog2w4Dv4l 0.591058 1.883454 -1.608613 -0.502516\nkV7mfdFcF9 0.629642 -0.474377 0.567357 1.658445\n.......\nDataFrame: Contains missing values:\nA B C D\ni6i6Xn9l9c -0.299335 0.410871 -0.431840 -0.302177\nOGo5KNNYNJ -0.174594 -1.366146 0.435063 -2.779446\nu0mG9q1L7C 1.019094 -0.061077 -1.138138 -0.218460\nRNJGqpci4o -0.380815 0.189970 -2.148521 -1.163589\nvXIcxItZ1D NaN -0.079448 0.604777 0.065290\n........\nDataFrame: Contains datetime values:\nA B C D\n2000-01-03 0.665402 0.860808 -0.180986 -0.970889\n2000-01-04 -1.511533 0.487539 -0.710355 -0.807816\n2000-01-05 -0.773294 0.197918 -1.214035 1.049529\n2000-01-06 -1.074894 1.774147 -0.620025 0.740779\n.......\nDataFrame: Contains mixed values:\nA B C D\n0 0.0 0.0 foo1 2009-01-01\n1 1.0 1.0 foo2 2009-01-02\n2 2.0 0.0 foo3 2009-01-05\n3 3.0 1.0 foo4 2009-01-06\n4 4.0 0.0 foo5 2009-01-07'

In [ ]:
""""""""""""""""""""""""""""74. Write a Pandas program to fill missing values in time series data.
From Wikipedia , in the mathematical field of numerical analysis, interpolation is a type of estimation, a method of constructing new data points within the range of a discrete set of known data points.
Sample Output:
Original DataFrame:
c1 c2
2000-01-03 120.0 7.0
2000-01-04 130.0 NaN
2000-01-05 140.0 10.0
2000-01-06 150.0 NaN
2000-01-07 NaN 5.5
2000-01-10 170.0 16.5
DataFrame after interpolate:
c1 c2
2000-01-03 120.0 7.00
2000-01-04 130.0 8.50
2000-01-05 140.0 10.00
2000-01-06 150.0 7.75
2000-01-07 160.0 5.50
2000-01-10 170.0 16.50""""""""""""""""""""""""""""

SyntaxError: unterminated string literal (detected at line 19) (<ipython-input-148-cbad131f8f7b>, line 19)

In [ ]:
import pandas as pd

# Creating the original DataFrame
data = {'c1': [120.0, 130.0, 140.0, 150.0, None, 170.0],
        'c2': [7.0, None, 10.0, None, 5.5, 16.5]}
index = pd.date_range('2000-01-03', periods=6, freq='D')
df = pd.DataFrame(data, index=index)

print("Original DataFrame:")
print(df)

# Interpolating missing values
df_interpolated = df.interpolate()

print("\nDataFrame after interpolate:")
print(df_interpolated)

In [ ]:
"""75. Write a Pandas program to use a local variable within a query.
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83
Values which are less than maximum value of 'W' column
W X Y Z
0 68 78 84 86
1 75 85 94 97
3 80 80 83 72
4 66 86 86 83"""

In [ ]:
data = {'name': [1, 2, 3, 4, 11],
        'score': [4, 5, 6, 9, 5],
        'attempts': [7, 8, 12, 1, 11],
        'qualify' : [1, 2, 3, 4, 5]}

df = pd.DataFrame(data)

df[df['name'] > df['score'].max()]

In [ ]:
"""76. Write a Pandas program to clean object column with mixed data of a given DataFrame using regular expression.
Sample Output:
Original dataframe:
agent purchase
0 a001 4500
1 a002 7500
2 a003 $3000.25
3 a003 $1250.35
4 a004 9000.00
Data Types:
0 <class 'float'>
1 <class 'float'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
Name: purchase, dtype: object
New Data Types:
0 <class 'float'>
1 <class 'float'>
2 <class 'float'>
3 <class 'float'>
4 <class 'float'>
Name: purchase, dtype: object"""

In [ ]:
data = {'name': [1, 2, 3, 4, 7],
        'score': [4, 5, 6, 9, 5],
        'attempts': ['7.0', '$8', '12%', '1', '11'],
        'qualify' : [1, 2, 3, 4, 5]}

df = pd.DataFrame(data)
df['attempts'] = df['attempts'].replace({'$8' : '8',
                                         '12%' : '12'}).astype(float)

df['attempts'].apply(type)

In [ ]:
"""77. Write a Pandas program to get the numeric representation of an array by identifying distinct values of a given column of a dataframe.
Sample Output:
Original DataFrame:
Name Date_Of_Birth Age
0 Alberto Franco 17/05/2002 18.5
1 Gino Mcneill 16/02/1999 21.2
2 Ryan Parkes 25/09/1998 22.5
3 Eesha Hinton 11/05/2002 22.0
4 Gino Mcneill 15/09/1997 23.0
Numeric representation of an array by identifying distinct values:
[0 1 2 3 1]
Index(['Alberto Franco', 'Gino Mcneill', 'Ryan Parkes', 'Eesha Hinton'], dtype='object')"""

In [ ]:
data = {'Name': ['Alberto Franco', 'Gino Mcneill', 'Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill'],
        'Date_Of_Birth': ['17/05/2002', '16/02/1999', '25/09/1998', '11/05/2002', '15/09/1997'],
        'Age': [18.5, 21.2, 22.5, 22.0, 23.0]}
df = pd.DataFrame(data)

label, name = pd.factorize(df['Name'])

list(label), (name)

In [ ]:
"""78. Write a Pandas program to replace the current value in a dataframe column based on last largest value. If the current value is less than last largest value replaces the value with 0.
Test data:
rnum
0 23
1 21
2 27
3 22
...
10 34
11 19
12 31
13 32
14 19
Sample Output:
Original DataFrame:
rnum
0 23
1 21
2 27
3 22
...
10 34
11 19
12 31
13 32
14 19
Replace current value in a dataframe column based on last largest value:
rnum
0 23
1 0
2 27
3 0
...
10 34
11 0
12 0
13 0
14 0"""

In [ ]:
data = {"nums" : [1, 2, 3, 1, 5, 1, 7, 8, 9, 10]}

df = pd.DataFrame(data)


largest = 0
for i in df['nums']:
  if i < largest:
    df['nums'] = df['nums'].replace(i, 0)
  else:
    largest = i

df

In [ ]:
"""79. Write a Pandas program to create a DataFrame from the clipboard (data from an Excel spreadsheet or a Google Sheet).
Sample Output:
Data from clipboard to DataFrame:
1 2 3 4
0 2 3 4 5
1 4 5 1 0
2 2 3 7 8"""

In [ ]:
df = pd.read_clipboard(header=None)
df

In [ ]:
"""80. Write a Pandas program to check for inequality of two given DataFrames.
Sample Output:
Original DataFrames:
W X Y Z
0 68.0 78.0 84 86
1 75.0 85.0 94 97
2 86.0 NaN 89 96
3 80.0 80.0 83 72
4 NaN 86.0 86 83
W X Y Z
0 78.0 78 84 86
1 75.0 85 84 97
2 86.0 96 89 96
3 80.0 80 83 72
4 NaN 76 86 83
Check for inequality of the said dataframes:
W X Y Z
0 True False False False
1 False False True False
2 False True False False
3 False False False False
4 True True False False"""

In [ ]:
data1 = {'W': [68.0, 75.0, 86.0, 80.0, np.nan],
         'X': [78.0, 85.0, np.nan, 80.0, 86.0],
         'Y': [84, 94, 89, 83, 86],
         'Z': [86, 97, 96, 72, 83]}
df1 = pd.DataFrame(data1)

data2 = {'W': [78.0, 75.0, 86.0, 80.0, np.nan],
         'X': [78, 85, 96, 80, 76],
         'Y': [84, 84, 89, 83, 86],
         'Z': [86, 97, 96, 72, 83]}
df2 = pd.DataFrame(data2)



df1.ne(df2)

In [ ]:
"""81. Write a Pandas program to get lowest n records within each group of a given DataFrame.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
Lowest n records within each group of a DataFrame:
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
col1 col2 col3
5 11 0 11
0 1 4 7
1 2 5 5
col1 col2 col3
4 7 5 1
1 2 5 5
0 1 4 7"""

In [ ]:
data = """
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
"""
data = {'col1' : [1, 2, 3, 4, 7, 11],}



print(df.nsmallest(3, 'col1'))
print(df.nsmallest(3, 'col2'))
print(df.nsmallest(3, 'col3'))

In [ ]:
df.Full()

In [ ]:
df.dump()

In [ ]:
df.print_full()

In [ ]:
df.to_string()

In [ ]:
"""1. Given a CSV file named 'data.csv', write a Python script using Pandas to load this file into a DataFrame and display the first 10 rows.
2. Assuming you have a DataFrame named df with columns 'Name', 'Age', and 'City', write a Python code snippet to add a new column 'Senior' that marks 'Yes' if the age is over 60 and 'No' otherwise.
3. Write a function using Pandas that takes a DataFrame and a column name as inputs and returns the mean value of that column, handling any missing values by ignoring them.
4. Given a DataFrame df with a column 'Date' containing dates in the format 'YYYY-MM-DD', write a script to convert this column to datetime type and then create a new column 'Year' that contains only the year part.
5. Assuming you have two DataFrames, df1 and df2, which share a common column 'ID', write a Pandas code snippet to merge these two DataFrames into one based on the 'ID' column using an inner join.
6. Write a code snippet that reshapes a DataFrame df from wide format to long format, where the column 'Variable' becomes the identifier variable, and the columns 'Jan', 'Feb', 'Mar' become part of a single column named 'Month' with their corresponding values under a new column 'Value'.
7. You have a DataFrame df with columns 'Product', 'Sales', and 'Month'. Write a Python script using Pandas to group the data by 'Month' and calculate the total sales per month.
8. Given a DataFrame df that includes a column 'Timestamp' with datetime objects, write a Python script that filters out rows where the 'Timestamp' is within the last 30 days from today.
9. Write a Python function that takes a DataFrame and a list of columns and returns a new DataFrame with only those columns, ensuring all column names in the list exist in the original DataFrame to avoid runtime errors.
10. Given a DataFrame df with a large amount of data, write a script that efficiently finds and prints the top 3 most frequent values in the 'Category' column along with their counts."""

In [ ]:
pd.read_csv('/drive/MyDrive/data')

In [ ]:
"""Load and Display Data:
Load the data from 'employees.csv' into a DataFrame and display the first 5 rows.
Data Modification:
Add a new column 'Senior' to the DataFrame that marks 'Yes' if the employee's age is over 40 and 'No' otherwise.
Data Filtering:
Filter and display employees who belong to the 'Finance' department and have a salary greater than $65,000.
Data Sorting and Grouping:
Group employees by 'Department' and calculate the average salary in each department.
Sort the result by average salary in descending order.
Column Deletion:
Delete the 'Age' column from the DataFrame.
Row Insertion:
Add a new row to the DataFrame for an employee: [9, "Emily White", 35, "Marketing", 45000].
Search Operations:
Search for any employee named 'Maria Garcia' and display her details.
Save Modified Data:
Save the modified DataFrame back to a new CSV file named 'updated_employees.csv'"""

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/testdata.csv')
df.head(5)

In [ ]:
df['Senior'] = [1, 1, 1, 1, 1, 1, 1, 1]

def issenior(age):
  if age > 40:
    return 'Yes'
  else:
    return 'No'


df['Senior'] = df['Age'].apply(issenior)
df

In [ ]:
df[(df['Department'] == 'Finance') & (df['Salary'] > 65000)]

In [ ]:
dfgroup = df.groupby('Department')

In [ ]:
df.drop('Age', axis='columns')
df

In [ ]:
df.loc[9] = [9, "Emily White", 35, "Marketing", 45000, 'Yes']
df

In [ ]:
df.to_csv('updated_employees')

In [ ]:
"""1. Write a Pandas program to split the following dataframe into groups based on school code. Also check the type of GroupBy object.
Test Data:

   school class            name date_Of_Birth   age  height  weight  address
S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_Of_Birth ': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [12, 12, 13, 13, 14, 12],
    'height': [173, 192, 186, 167, 151, 159],
    'weight': [35, 32, 33, 30, 31, 32],
    'address': ['street1', 'street2', 'street3', 'street1', 'street2', 'street4']},
    index=['S1', 'S2', 'S3', 'S4', 'S5', 'S6'])

grouped = df.groupby('school_code')

for i in grouped:
  print(i)

In [ ]:
"""2. Write a Pandas program to split the following dataframe by school code and get mean, min, and max value of age for each school.
Test Data:

   school class            name date_Of_Birth   age  height  weight  address
S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
grouped.agg({'age' : ['mean', 'max', 'min']})

In [ ]:
"""3. Write a Pandas program to split the following given dataframe into groups based on school code and class.
Test Data:

   school class            name date_Of_Birth   age  height  weight  address
S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
grouped2 = df.groupby(['school_code', 'class'])
for i in grouped2:
  print(i)

In [ ]:
"""4. Write a Pandas program to split the following given dataframe into groups based on school code and cast grouping as a list.
Test Data:

   school class            name date_Of_Birth   age  height  weight  address
S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
list(grouped)

In [ ]:
"""5. Write a Pandas program to split the following given dataframe into groups based on single column and multiple columns. Find the size of the grouped data.
Test Data:

   school class            name date_Of_Birth   age  height  weight  address
S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
grouped2.size()

In [ ]:
  """6. Write a Pandas program to split the following given dataframe into groups based on school code and call a specific group with the name of the group.
  Test Data:

    school class            name date_Of_Birth   age  height  weight  address
  S1   s001     V  Alberto Franco     15/05/2002   12    173      35  street1
  S2   s002     V    Gino Mcneill     17/05/2002   12    192      32  street2
  S3   s003    VI     Ryan Parkes     16/02/1999   13    186      33  street3
  S4   s001    VI    Eesha Hinton     25/09/1998   13    167      30  street1
  S5   s002     V    Gino Mcneill     11/05/2002   14    151      31  street2
  S6   s004    VI    David Parkes     15/09/1997   12    159      32  street4"""

In [ ]:
grouped.get_group('s001')

In [ ]:
"""7. Write a Pandas program to split a dataset, group by one column and get mean, min, and max values by group. Using the following dataset find the mean, min, and max values of purchase amount (purch_amt) group by customer id (customer_id).
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001"""

In [ ]:
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3001,3001,3005,3001,3005,3001,3005,3001,3005,3001,3005,3005],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5006,5003,5002,5007,5001]})

grouped = df.groupby('purch_amt')
#grouped.agg(['mean', 'min', 'max'])

df.groupby('customer_id').agg({'purch_amt': ['mean', 'min', 'max']})

In [ ]:
"""8. Write a Pandas program to split a dataset to group by two columns and count by each row.
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001"""

In [ ]:
df.groupby(['customer_id', 'salesman_id']).size().reset_index()

In [ ]:
"""9. Write a Pandas program to split a dataset to group by two columns and then sort the aggregated results within the groups.
In the following dataset group on 'customer_id', 'salesman_id' and then sort sum of purch_amt within the groups.
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001"""

In [ ]:
group = df.groupby(['customer_id', 'salesman_id'])
groupagg = group.agg({'purch_amt':'sum'})
groupaggfr = groupagg['purch_amt'].groupby(level=0, group_keys = False)
print(groupaggfr.nlargest())

In [ ]:
"""10. Write a Pandas program to split the following dataframe into groups based on customer id and create a list of order date for each group.
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5006
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5007
11   70013    3045.60  2012-04-25         3002         5001"""

In [ ]:
id = df.groupby('customer_id')

id['ord_date'].apply(list)

In [ ]:
"""11. Write a Pandas program to split the following dataframe into groups and calculate monthly purchase amount.
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  05-10-2012         3001         5002
1    70009     270.65  09-10-2012         3001         5005
2    70002      65.26  05-10-2012         3005         5001
3    70004     110.50  08-17-2012         3001         5003
4    70007     948.50  10-09-2012         3005         5002
5    70005    2400.60  07-27-2012         3001         5001
6    70008    5760.00  10-09-2012         3005         5001
7    70010    1983.43  10-10-2012         3001         5006
8    70003    2480.40  10-10-2012         3005         5003
9    70012     250.45  06-17-2012         3001         5002
10   70011      75.29  07-08-2012         3005         5007
11   70013    3045.60  04-25-2012         3005         5001"""

In [ ]:
df["ord_date"] = pd.to_datetime(df['ord_date'])
df.set_index('ord_date').groupby(pd.Grouper(freq='M')).agg({'purch_amt' : 'sum'})

In [ ]:
df.set_index('ord_date').groupby(pd.Grouper(freq='Y')).agg({'purch_amt' : 'sum'})

In [ ]:
df["ord_date"] = pd.to_datetime(df['ord_date'])
df.set_index('ord_date').groupby(pd.Grouper(freq='M')).agg({'customer_id' : 'count'})

In [ ]:
"""12. Write a Pandas program to split the following dataframe into groups, group by month and year based on order date and find the total purchase amount year wise, month wise.
Test Data:

    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  05-10-2012         3001         5002
1    70009     270.65  09-10-2012         3001         5005
2    70002      65.26  05-10-2012         3005         5001
3    70004     110.50  08-17-2012         3001         5003
4    70007     948.50  10-09-2012         3005         5002
5    70005    2400.60  07-27-2012         3001         5001
6    70008    5760.00  10-09-2012         3005         5001
7    70010    1983.43  10-10-2012         3001         5006
8    70003    2480.40  10-10-2012         3005         5003
9    70012     250.45  06-17-2012         3001         5002
10   70011      75.29  07-08-2012         3005         5007
11   70013    3045.60  04-25-2012         3005         5001"""

In [ ]:
df["ord_date"] = pd.to_datetime(df['ord_date'])
df.groupby([df['ord_date'].dt.year,df['ord_date'].dt.month]).agg({'purch_amt' : 'sum'})

In [ ]:
df["ord_date"] = pd.to_datetime(df['ord_date'])
df.groupby([df['ord_date'].dt.year,df['ord_date'].dt.month, df['ord_date'].dt.weekday, df['ord_date'].dt.day]).agg({'purch_amt' : 'sum'})

In [ ]:
"""13. Write a Pandas program to split the following dataframe into groups based on first column and set other column values into a list of values.
Test Data:

    X   Y   Z
0  10  10  22
1  10  15  20
2  10  11  18
3  20  20  20
4  30  21  13
5  30  12  10
6  10  14   0"""

In [ ]:
df = pd.DataFrame( {'X' : [10, 10, 10, 20, 30, 30, 10],
                    'Y' : [10, 15, 11, 20, 21, 12, 14],
                    'Z' : [22, 20, 18, 20, 13, 10, 0]})

df.groupby('X').aggregate(lambda tdf: tdf.unique().tolist())

[link text](https://)Load the dataset using pandas.
Fill missing values in Price with the average price of the corresponding Product_ID.
Replace missing values in Quantity_Sold with the median quantity sold of all products.
Standardize the Store_Location to title case (e.g., "new york" should be "New York").
Save the cleaned data to a new CSV file, cleaned_sales_data.csv.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Sales_Data.csv')
df

In [ ]:
idgroup = df.groupby('Product_ID')
idmeans = idgroup['Price'].agg(['mean'])

In [ ]:
df['Price'] = idgroup['Price'].transform(lambda row: row.fillna(row.mean()))
df

In [ ]:
df['Quantity_Sold'] = df['Quantity_Sold'].transform(lambda row: row.fillna(row.median()))
df

In [ ]:
df['Store_Location'] = df['Store_Location'].str.title()
df

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/cleaned_sales_data.csv')

Calculate the total revenue (Price * Quantity_Sold) per store.
Find the top 3 products by total revenue in each store.
Determine the month with the highest overall sales across all stores.

In [ ]:
df['Product_Rev'] = df['Quantity_Sold']*df['Price']
storev = df.groupby('Store_Location')['Product_Rev'].sum().reset_index(name='totalrev')
storev

In [ ]:
storloc = df.groupby(['Store_Location', 'Product_ID']).agg({"Product_Rev" : "sum"}).reset_index()
storloc.sort_values(by=['Store_Location', 'Product_Rev'], ascending=[True, False]).groupby('Store_Location').head(3)

In [ ]:
df['Rev'] = df['Price']*df['Quantity_Sold']
df["Date"] = pd.to_datetime(df['Date'])
months = df.set_index('Date').groupby(pd.Grouper(freq='M'))
months['Rev'].sum().nlargest(1)

What is the average rating for apps in the dataset?
Calculate the average score for all apps.

Which genre has the highest number of installations?
Sum the min_installs for each genre and identify the genre with the highest total installations.

What proportion of apps offer in-app purchases (offers_iap)?
Determine the percentage of apps that offer in-app purchases versus those that do not.

How does advertising support impact app ratings?
Compare the average score of apps that are ad-supported (ad_supported) with those that are not.

What are the top 5 apps with the highest number of five-star ratings?
Identify the top five apps based on the rating_five_star column.

How has the number of reviews changed over time for the most popular genres?
For the genres with the highest installations, plot the trend of reviews over the released dates.

What is the average number of ratings per day for apps in different price categories?
Group the apps by their price (free vs paid) and calculate the average ratings_per_day for each group.

Which apps have the highest disparity between one-star and five-star ratings?
Calculate the difference between rating_one_star and rating_five_star for each app and identify those with the largest disparities.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/googleplaystoredata.csv')
df

,app_id,title,...,rating_four_star,rating_five_star
0,com.prettyteengames.royal.princess.wedding.mak...,Royal Princess Wedding Makeover and Dress Up,...,90,689
1,com.MayGreenStudio.dressup,Momo's Dressup,...,2561,21721
2,air.theflash.f2game.PrettyGirl23,Princess Pretty Girl,...,528,3207
3,air.com.dressupone.animeschooluniforms,Anime School Uniforms,...,668,4068
4,air.theflash.f2game.PrettyGirl7,Wedding Pretty girl,...,414,2471
...,...,...,...,...,...
62689,com.yunbu.balala.magicdress3.free,Magic Princess Dress 3,...,650,4054
62690,air.com.dressupone.lateforclass,"Dress Up Games, Late For Class",...,1506,8441
62691,com.magicdress.cinderella.ice.princess.free,Magic Princess Dress 2,...,914,4536
62692,com.gamesforgirlsfree.animeprincess,Anime Princess Dress Up,...,357,2410
62693,com.ninepixel.whitehorseprincessandroid,White Horse Princess Dress Up,...,581,3586

Warning: Total number of columns (22) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (62694) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
# Average score of all apps
df['score'].mean()

4.221623968066303

In [ ]:
# Genre with most installations
genres = df.groupby('genre')
genres['min_installs'].sum().nlargest(1)

genre
Tools    19324157224
Name: min_installs, dtype: int64

In [ ]:
# Proportion of apps that offer in-app purchases
offer = df[df['offers_iap'] == True].count()
(offer['title']/df.shape[0])*100

21.69745111174913

In [ ]:
# Check how supporting ads affects ratings
ads = df.groupby('ad_supported')
ads['score'].mean()

ad_supported
False    4.088688
True     4.327992
Name: score, dtype: float64

In [ ]:
# Top 5 apps with five star ratings
df.nlargest(5, 'rating_five_star')[['title', 'rating_five_star']]

,title,rating_five_star
5058,WhatsApp Messenger,52952655
7119,Instagram,51812869
5298,Facebook,48869643
12054,Clash of Clans,37224307
5293,Messenger – Text and Video Chat for Free,35988340

In [ ]:
# Ratings per day for free apps vs paid apps
def free(price):
  if price == 0:
    return 'Free'
  else:
    return 'Paid'
df['Cost'] = df['price'].apply(free)

cost = df.groupby('Cost')
cost['ratings_per_day'].mean()

Cost
Free    41.648264
Paid     1.828194
Name: ratings_per_day, dtype: float64

In [ ]:
# Biggest difference in one star and five star reviews
df['rate_diff'] = df['rating_five_star'] - df['rating_one_star']
df.nlargest(5, 'rate_diff')[['title', 'rate_diff']]

,title,rate_diff
7119,Instagram,48969091
5058,WhatsApp Messenger,48349133
5298,Facebook,39210928
12054,Clash of Clans,35233511
4484,Clean Master- Space Cleaner & Antivirus,33243430

# **Home Work**

1. Which app genres have the best average ratings?

In [ ]:
genres = df.groupby('genre')
genres['score'].mean().nlargest(3)

genre
Books & Reference    4.515021
Word                 4.494153
Personalization      4.476157
Name: score, dtype: float64

2. Which apps have the most significant growth in installations over time?

In [ ]:
import datetime as dt
def days_rel(date):
  days = dt.datetime.now() - date
  return days.days
df['released'] = pd.to_datetime(df['released'])
df['days_released'] = df['released'].apply(days_rel)
df['growth'] = df['min_installs'] / df['days_released']
df.nlargest(5, columns='growth')[['title', 'growth']]

,title,growth
53181,Google Photos,304692.260817
34442,Android System WebView,297530.496876
5293,Messenger – Text and Video Chat for Free,265604.249668
45449,Google Text-to-Speech,257931.390250
8468,Google Play Games,252844.500632

3. Which apps maintain high ratings with a high number of installs?

In [ ]:
df.nlargest(5, columns=['score', 'min_installs'])[['title', 'score', 'min_installs']]

,title,score,min_installs
19757,Vortex Cloud Gaming,5.0,5000000
40461,Android TV Remote Service,5.0,5000000
19046,Star Combat Online,5.0,1000000
54954,Skype Preview,5.0,1000000
12610,Niagara Launcher 🔹 fresh & clean,5.0,100000

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Loans.csv')
df = df.dropna(axis=1)
df

<ipython-input-31-9154bacb415b>:2: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Loans.csv')

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,policy_code,application_type,acc_now_delinq,delinq_amnt
0,1077501,1296599,5000,5000,4975.0,36 months,10.65%,162.87,B,B2,...,5000.00,863.16,0.00,0.00,0.00,171.62,1,INDIVIDUAL,0,0
1,1077430,1314167,2500,2500,2500.0,60 months,15.27%,59.83,C,C4,...,456.46,435.17,0.00,117.08,1.11,119.66,1,INDIVIDUAL,0,0
2,1077175,1313524,2400,2400,2400.0,36 months,15.96%,84.33,C,C5,...,2400.00,605.67,0.00,0.00,0.00,649.91,1,INDIVIDUAL,0,0
3,1076863,1277178,10000,10000,10000.0,36 months,13.49%,339.31,C,C1,...,10000.00,2214.92,16.97,0.00,0.00,357.48,1,INDIVIDUAL,0,0
4,1075358,1311748,3000,3000,3000.0,60 months,12.69%,67.79,B,B5,...,2475.94,1037.39,0.00,0.00,0.00,67.79,1,INDIVIDUAL,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39712,92187,92174,2500,2500,1075.0,36 months,8.07%,78.42,A,A4,...,2500.00,322.97,0.00,0.00,0.00,80.90,1,INDIVIDUAL,0,0
39713,90665,90607,8500,8500,875.0,36 months,10.28%,275.38,C,C1,...,8500.00,1413.49,0.00,0.00,0.00,281.94,1,INDIVIDUAL,0,0
39714,90395,90390,5000,5000,1325.0,36 months,8.07%,156.84,A,A4,...,5000.00,272.16,0.00,0.00,0.00,0.00,1,INDIVIDUAL,0,0
39715,90376,89243,5000,5000,650.0,36 months,7.43%,155.38,A,A2,...,5000.00,174.20,0.00,0.00,0.00,0.00,1,INDIVIDUAL,0,0
39716,87023,86999,7500,7500,800.0,36 months,13.75%,255.43,E,E2,...,7500.00,1695.26,0.00,0.00,0.00,256.59,1,INDIVIDUAL,0,0

Warning: Total number of columns (45) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (39717) exceeds max_rows (20000). Limiting to first (20000) rows.

How many loans are there in each unique loan status category?
Use value_counts() to find out how many loans fall into each category of loan status (e.g., fully paid, charged off, current).

What is the average loan amount for each type of loan status?
Group the data by loan status and calculate the average loan amount for each category.

Which year had the highest number of loan issuances recorded in the dataset?
Assuming there's a 'date' or 'year' column, you can use pd.to_datetime() to convert it into datetime format and then use dt.year to extract the year for grouping

In [ ]:
df['loan_status'].value_counts()

loan_status
Fully Paid     32950
Charged Off     5627
Current         1140
Name: count, dtype: int64

In [ ]:
status = df.groupby('loan_status')
status['loan_amnt'].mean()

loan_status
Charged Off    12104.385108
Current        17053.991228
Fully Paid     10866.455994
Name: loan_amnt, dtype: float64

In [ ]:
df['issue_d'] = pd.to_datetime(df['issue_d'], format='%b-%y', yearfirst=False)
df['c'] = [1]*df.shape[0]
years = df.groupby('issue_d')
years['c'].sum().nlargest(1)

issue_d
2011-12-01    2260
Name: c, dtype: int64

What are the top 5 zip codes with the highest average loan amounts?
Group the dataset by zip code and then calculate the mean loan amount for each, sorting by the highest averages.


What percentage of loans are charged off compared to the total number of loans?
Calculate the proportion of loans with the status 'charged-off' against the total number of loans.

In [ ]:
zips = df.groupby('zip_code')
zips['loan_amnt'].mean().nlargest(5)

zip_code
556xx    25000.0
834xx    25000.0
248xx    24250.0
465xx    22550.0
743xx    21725.0
Name: loan_amnt, dtype: float64

In [ ]:
status = df.groupby('loan_status')
f"{round(status.get_group('Charged Off')['loan_status'].count() / df.shape[0] * 100, 2)}%"

'14.17%'

Create a new column that categorizes loans into 'small', 'medium', and 'large' based on the loan amount.
Define thresholds for each category and use pd.cut() or np.select() to create this new categorical column.

In [ ]:
df['size'] = pd.cut(df['loan_amnt'], bins=[0, 5000, 15000, float('inf')], labels=['small', 'medium', 'large'])
df[['loan_amnt', 'size']]

       loan_amnt    size
0           5000   small
1           2500   small
2           2400   small
3          10000  medium
4           3000   small
...          ...     ...
39712       2500   small
39713       8500  medium
39714       5000   small
39715       5000   small
39716       7500  medium

[39717 rows x 2 columns]

In [ ]:
# Average interest rate
def perctonum(perc):
  perc = str(perc)
  return float(perc.strip()[:-1])

df['int_rate'] = df['int_rate'].apply(perctonum)
sizes = df.groupby('size')
sizes['int_rate'].mean()

size
small     10.607964
medium    10.990595
large     13.349669
Name: int_rate, dtype: float64

For each loan size category (small, medium, large), what is the default rate?
First, find the number of defaults in each category, then divide by the total number of loans in that category.

In [ ]:
(sizes['loan_status'].value_counts().loc[:, 'Charged Off']/sizes['loan_status'].count())*100

size
small     13.733278
medium    12.875967
large     17.559491
dtype: float64

Data Loading and Inspection

How would you load the Iris dataset into a Pandas DataFrame from a CSV file?
Write a Pandas command to display the first 10 rows of the dataset.
Use Pandas to show a summary of statistics for numerical columns in the Iris dataset.

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
df.rename(columns={'sepal length (cm)' : 'sepal_len',
                   'sepal width (cm)' : 'sepal_wid',
                   'petal length (cm)' : 'petal_len',
                   'petal width (cm)' : 'petal_wid'}, inplace=True)
df

     sepal_len  sepal_wid  petal_len  petal_wid  species
0          5.1        3.5        1.4        0.2        0
1          4.9        3.0        1.4        0.2        0
2          4.7        3.2        1.3        0.2        0
3          4.6        3.1        1.5        0.2        0
4          5.0        3.6        1.4        0.2        0
..         ...        ...        ...        ...      ...
145        6.7        3.0        5.2        2.3        2
146        6.3        2.5        5.0        1.9        2
147        6.5        3.0        5.2        2.0        2
148        6.2        3.4        5.4        2.3        2
149        5.9        3.0        5.1        1.8        2

[150 rows x 5 columns]

In [ ]:
df.head(10)

   sepal_len  sepal_wid  petal_len  petal_wid  species
0        5.1        3.5        1.4        0.2        0
1        4.9        3.0        1.4        0.2        0
2        4.7        3.2        1.3        0.2        0
3        4.6        3.1        1.5        0.2        0
4        5.0        3.6        1.4        0.2        0
5        5.4        3.9        1.7        0.4        0
6        4.6        3.4        1.4        0.3        0
7        5.0        3.4        1.5        0.2        0
8        4.4        2.9        1.4        0.2        0
9        4.9        3.1        1.5        0.1        0

In [ ]:
df.describe()

        sepal_len   sepal_wid   petal_len   petal_wid     species
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

How would you use Pandas to select only the columns pertaining to petal length and petal width?
Write a Pandas command to filter the data to show only those records where the sepal length is greater than the average sepal length.
Using Pandas, how can you create a new column that categorizes the petal length into 'short', 'medium', and 'long'?

In [ ]:
df[['petal_len', 'petal_wid']]

     petal_len  petal_wid
0          1.4        0.2
1          1.4        0.2
2          1.3        0.2
3          1.5        0.2
4          1.4        0.2
..         ...        ...
145        5.2        2.3
146        5.0        1.9
147        5.2        2.0
148        5.4        2.3
149        5.1        1.8

[150 rows x 2 columns]

In [ ]:
df[df['sepal_len'] > df['sepal_len'].mean()]

     sepal_len  sepal_wid  petal_len  petal_wid  species
50         7.0        3.2        4.7        1.4        1
51         6.4        3.2        4.5        1.5        1
52         6.9        3.1        4.9        1.5        1
54         6.5        2.8        4.6        1.5        1
56         6.3        3.3        4.7        1.6        1
..         ...        ...        ...        ...      ...
145        6.7        3.0        5.2        2.3        2
146        6.3        2.5        5.0        1.9        2
147        6.5        3.0        5.2        2.0        2
148        6.2        3.4        5.4        2.3        2
149        5.9        3.0        5.1        1.8        2

[70 rows x 5 columns]

In [ ]:
df['petal_size'] = pd.cut(df['petal_len'], bins=[0, 2, 4, 100000000], labels=['Short', 'Medium', 'Long'])
df

     sepal_len  sepal_wid  petal_len  petal_wid  species petal_size
0          5.1        3.5        1.4        0.2        0      Short
1          4.9        3.0        1.4        0.2        0      Short
2          4.7        3.2        1.3        0.2        0      Short
3          4.6        3.1        1.5        0.2        0      Short
4          5.0        3.6        1.4        0.2        0      Short
..         ...        ...        ...        ...      ...        ...
145        6.7        3.0        5.2        2.3        2       Long
146        6.3        2.5        5.0        1.9        2       Long
147        6.5        3.0        5.2        2.0        2       Long
148        6.2        3.4        5.4        2.3        2       Long
149        5.9        3.0        5.1        1.8        2       Long

[150 rows x 6 columns]

How can you use Pandas to group the dataset by species and calculate the mean of each numerical feature?
Write a command to find the maximum sepal width for each species using Pandas.
Use Pandas to calculate the total number of samples for each species in the dataset.

In [ ]:
species = df.groupby('species')
species.agg({'sepal_len' : 'mean',
             'sepal_wid' : 'mean',
             'petal_len' : 'mean',
             'petal_wid' : 'mean'})

         sepal_len  sepal_wid  petal_len  petal_wid
species
0            5.006      3.428      1.462      0.246
1            5.936      2.770      4.260      1.326
2            6.588      2.974      5.552      2.026

In [ ]:
species.agg({'sepal_wid' : 'max'})

         sepal_wid
species
0              4.4
1              3.4
2              3.8

In [ ]:
species['sepal_len'].count()

species
0    50
1    50
2    50
Name: sepal_len, dtype: int64

If there were missing values in the dataset, how would you use Pandas to fill them with the median of their respective column?
Using Pandas, how would you remove duplicate entries from the dataset, if any?

In [119]:
df.median()

TypeError: 'Categorical' with dtype category does not support reduction 'median'